### ISSUE TITLE
Planet's templates NoReverseMatch error

### ISSUE THREAD

**Issue by MissFilly** [PyAr/pyarweb#108]
All Planet's templates including the line `{% url 'planet_tag_detail' tag.name %}` are throwing `NoReverseMatch` error:

`Reverse for 'planet_tag_detail' with arguments '('<html>\n <body>\n  <p>\n   pc\n  <',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['planet/tags/(?P<tag>.*)/$']`

Same for `planet_by_tag_author_detail`:

`Reverse for 'planet_by_tag_author_detail' with arguments '(1, 'filly', '<html>\n <body>\n  <p>\n   pc\n  <')' and keyword arguments '{}' not found. 1 pattern(s) tried: ['planet/authors/(?P<author_id>\\d+)/(?P<slug>[a-zA-Z0-9_\\-]+)/tags/(?P<tag>.*)/$']`

**Comment by angvp** [comment]
@MissFilly @matagus creo que podemos cerrar esto ^ ? confirmen :)

**Comment by cmdelatorre** [comment]
Planet app fue removida en #416
