### ISSUE TITLE
"adopta un newbie" muestra una pantalla en blanco

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#126]
Qué se supone que es?

![captura de pantalla de 2014-11-18 14 43 41](https://cloud.githubusercontent.com/assets/2355719/5092859/665e05aa-6f31-11e4-85b3-5352d6a42e04.png)

**Comment by edvm** [comment]
Esto lo paso a Backlog, viene congelado hace un tiempo.
