### ISSUE TITLE
No se puede adjuntar archivos a paginas de la wiki

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#133]
El archivo parece subir, pero se queda la barra de progreso se queda al 100% y nunca se lista el nuevo adjunto

![captura de pantalla de 2014-11-18 15 57 12](https://cloud.githubusercontent.com/assets/2355719/5093997/d1db8a1e-6f3b-11e4-8f60-120ef71ca45c.png)

**Comment by edvm** [comment]
Nico, tenemos noticias de esto? :)

**Comment by mgaitan** [comment]
parece que funca correctamente. acabo de subir mi "firma digital" acá ;-)

http://beta.python.org.ar/wiki/AdoptaUnNewbie


si hay tiempo, estaria bueno verificar/configurar el backend para servir
los attachments que mejor nos calce a nuestro esquema.

http://waliki.readthedocs.org/en/latest/attachments.html
https://github.com/johnsensible/django-sendfile#simple-backend


On Sun, Mar 8, 2015 at 11:27 PM, Emiliano Dalla Verde Marcozzi <
notifications@github.com> wrote:

> Nico, tenemos noticias de esto? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/133#issuecomment-77791249>.
>



-- 
mgaitan.github.io
textosypretextos.com.ar <http://textosyprextextos.com.ar>

**Comment by gilgamezh** [comment]
Creo que esto nos quedó abierto y el problema estaba en otro lado. 
Si mi memoria no me falla el error se daba con circus. 

Cómo puedo configurar desde dónde se sirven los attachments? Es un setting?
Gracias!

**Comment by mgaitan** [comment]
2015-03-09 10:07 GMT-03:00 Nicolás Demarchi <notifications@github.com>:

> Cómo puedo configurar desde dónde se sirven los attachments? Es un setting?


waliki usa django-sendfile. de parte de django es sólo definir un setting,
pero dependiendo el server hay que hacer otras config fuera de django.

https://github.com/johnsensible/django-sendfile#simple-backend




-- 
mgaitan.github.io
textosypretextos.com.ar <http://textosyprextextos.com.ar>

**Comment by angvp** [comment]
Muchachos, antes de que este issue cumpla 1 año, podemos cerrarlo? @gilgamezh @mgaitan

**Comment by mgaitan** [comment]
+1

2016-02-24 23:01 GMT-03:00 Angel Velasquez <notifications@github.com>:

> Muchachos, antes de que este issue cumpla 1 año, podemos cerrarlo?
> @gilgamezh <https://github.com/gilgamezh> @mgaitan
> <https://github.com/mgaitan>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/133#issuecomment-188560114>.
>



-- 
mgaitan.github.io
textosypretextos.com.ar
