### ISSUE TITLE
Improvement: Busquedas Laborales

### ISSUE THREAD

**Issue by Nicogue** [PyAr/pyarweb#155]
Desconozco como se ira a implementar esta seccion pero heme aqui haciendo brainstorming a fin de colaborar de algun modo.

En el viejo sitio me resulto un poco incomoda la forma en la que se presentaba la información, en muchas secciones la información se muestra en un choclo interminable de palabras indigeribles por la retina.

-Estaría bueno que pasado un determinado tiempo las noticias los trabajos ofrecidos se auto oculten para hacer mas legible el contenido y con la opción de aplicar filtros tales como lugar, tecnologias y seniority.

![asdasda](https://cloud.githubusercontent.com/assets/1730996/5148668/e0f31eac-719f-11e4-84dc-26ad5bf0596e.png)

**Comment by edvm** [comment]
Ahora para poder crear un trabajo hay que estar logueado, sigo con el resto :)

**Comment by edvm** [comment]
Implementado!
