### ISSUE TITLE
Remover app y templates de "Proyectos de la comunidad"

### ISSUE THREAD

**Issue by tzenderman** [PyAr/pyarweb#175]

**Comment by edvm** [comment]
Acabo de hacer review, juan te olvidaste el commit xD ? porque sigo viendo la app 'projects' en el INSTALLED_APPS, y esta en el repo, tambien en pyarweb/urls.py. Vuelvo esta tarea a 'ready'

**Comment by edvm** [comment]
Ahora el link en la portada /index.html quedo apuntando a la wiki/Proyectos
