### ISSUE TITLE
Agregar url amigable con titulo de la oferta de trabajo en vez del id (SEO related)

### ISSUE THREAD

**Issue by edvm** [PyAr/pyarweb#185]

**Comment by angvp** [comment]
Ahora me armo de valor y hago un pull request, espérenlo en las próximas horas :D

**Comment by edvm** [comment]
Vaaaaamos Angel ! :D

2015-03-11 0:25 GMT-03:00 Angel Velasquez <notifications@github.com>:

> Ahora me armo de valor y hago un pull request, espérenlo en las próximas
> horas :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/185#issuecomment-78196595>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by angvp** [comment]
Fixed in #242
