### ISSUE TITLE
multiples issues en sección "Adopta un newbie"

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#200]
- [ ] la pantalla index tiene el markup roto
![captura de pantalla de 2014-12-11 17 55 44](https://cloud.githubusercontent.com/assets/2355719/5401952/fb2972f2-815e-11e4-9a33-5b3059abccf2.png)

- [ ] deberia tener al menos una breve introducción: para qué sirve, cómo funciona, etc. 

- [ ] los formularios de jedi y padawan (quiero aprender/etc) no tienen buen estilo (crispy_form ? )

![captura de pantalla de 2014-12-11 17 59 11](https://cloud.githubusercontent.com/assets/2355719/5401999/6da8ac44-815f-11e4-8dc7-ecf8a8578a63.png)

- [ ] si me registro como jedi, luego no puedo editar mi registro. Y me permite volver a completar el formulario desde 0 con este resultado 

![captura de pantalla de 2014-12-11 17 59 50](https://cloud.githubusercontent.com/assets/2355719/5402075/a2064c3a-815f-11e4-9cf9-0cbad6a48699.png)

- [ ] La lista de "jedis" en "quiero aprender" no lista los temas que el jedi ofrece

![captura de pantalla de 2014-12-11 18 01 05](https://cloud.githubusercontent.com/assets/2355719/5402092/bb23ecae-815f-11e4-9b42-db5702248462.png)

- [ ] "Enviar solicitud" falla si el usuario no está registrado como padawan

- [ ] Intereses deberia un TaggableManager como "etiquetas" de news

**Comment by llazzaro** [comment]
si voy a /newbie/
tengo un TypeError
int() argument must be a string or a number, not 'SimpleLazyObject'

no se si esto va aca o es un issue nuevo
