### ISSUE TITLE
Noticias Contenido muy largo rompe styles

### ISSUE THREAD

**Issue by llazzaro** [PyAr/pyarweb#206]
Si los contenidos de las imagenes son largos rompe los styles.
ver imagen

![prueba - pyar - python argentina](https://cloud.githubusercontent.com/assets/568181/5657676/ee1b1e58-96d0-11e4-84fb-3ff0df96be5d.png)

**Comment by cmdelatorre** [comment]
Esto parece haber sido solucionado ya.
