### ISSUE TITLE
RemovedInDjango18Warning: get_query_set method should be renamed `get_queryset`

### ISSUE THREAD

**Issue by surrealcristian** [PyAr/pyarweb#210]
Al ejecutar el comando "syncdb", se muestran por stdout varios alerts sobre la deprecación de la forma RemovedInDjango18Warning `PostManager.get_query_set` method should be renamed `get_queryset`.

**Comment by angvp** [comment]
¿Qué módulos especificamente? Puede ser un módulo externo.

**Comment by surrealcristian** [comment]
planet/managers.py
