### ISSUE TITLE
el titulo de las ofertas no aparece en el title de pagina

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#218]
en el titulo de la pagina (tag  `<title>`) en ofertas deberia aparece 

http://beta.python.org.ar/trabajo/2/

ejemplo 
"Programador Python - Ofertas laborales - PyAr...."

**Comment by edvm** [comment]
No entendi el issue, ahora mismo esta el titulo que se pone al agregar la
oferta de trabajo, y que es luego lo que se muestra, que es lo que falta?


2015-03-09 22:48 GMT-03:00 Martín Gaitán <notifications@github.com>:

> en el titulo de la pagina (tag <title>) en ofertas deberia aparece
>
> http://beta.python.org.ar/trabajo/2/
>
> ejemplo
> "Programador Python - Ofertas laborales - PyAr...."
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/218>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by mgaitan** [comment]
![captura de pantalla de 2015-03-09 23 47 18](https://cloud.githubusercontent.com/assets/2355719/6568462/a8cc33f8-c6b6-11e4-8b07-7bcebf3596ca.png)

el title de la ventana, en la indexacion de los buscadores tiene mucha prioridad y no dice nada sobre el trabajo en cuestion
