### ISSUE TITLE
paginador del buscador falla al recalcular total de paginas

### ISSUE THREAD

**Issue by g3r4benitez** [PyAr/pyarweb#220]
al buscar el texto: python or 1=1

el buscador muestra: aproximadamente 75 resultados y 8 páginas.

si accedo directamente a la pagina 4 del paginador, el mismo dice: 

aproximadamente 25 resultados y 3 páginas

**Comment by mgaitan** [comment]
el buscador que usamos es externo: https://www.google.com.ar/cse . como el google "normal", el dato de cuantos resultados se encontraron es aproximado

PD: gracias por estar probando el sitio!
