### ISSUE TITLE
Las busquedas no devuelven ningún resultado

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/pyarweb#225]
Hice pruebas con cosas como "python" "pycamp" "lista de correos"

Es una config?

**Comment by mgaitan** [comment]
mientes! ![captura de pantalla de 2015-03-10 20 10 28](https://cloud.githubusercontent.com/assets/2355719/6587335/b888735a-c761-11e4-8194-d1f89d78baf8.png)

puede ser tu browser que bloquea un javascript o algo asi? otras busquedas si te funcionan?

**Comment by gilgamezh** [comment]
Era una config... en mi browser. Ghostery está bloqueando la llamada a la api de google

![screenshot from 2015-03-10 20 18 26](https://cloud.githubusercontent.com/assets/1496486/6587399/6ea2ee9a-c762-11e4-8338-1756f0b4e95c.png)
