### ISSUE TITLE
No tenemos robots.txt

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/pyarweb#228]
Siempre es bueno tener uno bien configurado

Cuál sería la manera de hacerlo con django? si me tiran una punta yo lo hago.

**Comment by mgaitan** [comment]
si no queremos mucha sofisticacion, simplemente podemos escribir el robots.txt plano, ponerlo en una carpeta de templates y servirlo con django via un templateview

`url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'))`

**Comment by edvm** [comment]
El 10 de marzo de 2015, 21:27, Martín Gaitán <notifications@github.com>
escribió:

> si no queremos mucha sofisticacion, simplemente podemos escribir el
> robots.txt plano, ponerlo en una carpeta de templates y servirlo con django
> via un templateview
>
> url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',
> content_type='text/plain'))
>
>
> Genial solución Gaitán :)


-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by gilgamezh** [comment]
Configuré directamente en apache con un delay a ver si nos pegan con un poco mas de tranquilidad.

http://python.org.ar/robots.txt

En la semana voy a ponerle unas horas a ver de afinar la config del server porque no estámos quedando sin memoria y se cae el apache.

**Comment by cmdelatorre** [comment]
Dice @gilgamezh que lo solucionó
