### ISSUE TITLE
La página de un evento se rompe 

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/pyarweb#229]
Por ejemplo con un video
http://beta.python.org.ar/eventos/4/

**Comment by soysergiogomez** [comment]
hola @gilgamezh, estuve viendo la lista de los issues. No puedo reproducir este bug.
Puede ser que ya este solucionado?

**Comment by angvp** [comment]
Uff ya ni la url existe, pero creo que igual con unos cambios que metió @btenaglia se arregló eso, mañana lo intentamos reproducir y sino anda lo cerramos, gracias por el heads-up @soysergiogomez
