### ISSUE TITLE
Filtrar jobs por etiquetas no funciona

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#232]
idem #231 pero ademas 

- los tags en un el job (listado) no son links 

![captura de pantalla de 2015-03-11 00 32 36](https://cloud.githubusercontent.com/assets/2355719/6589858/2f4bbd7a-c786-11e4-8952-f0d8132e0aa6.png)

- no están los tags en el detalle de la oferta laboral

**Comment by llazzaro** [comment]
donde tienen que apuntar los tags? hay alguna vista?

tambi'en hay que mejorar el estilo del texto
![screenshot from 2015-03-11 21 33 27](https://cloud.githubusercontent.com/assets/568181/6609864/58085934-c836-11e4-8f5c-4982086cdf51.png)

si quieren hago este issue

**Comment by angvp** [comment]
Supongo que debería llevar a una pantalla de jobs que matcheen con el tag seleccionado, con lo cual el template estaría casi listo (sólo agregar los links), y habría que hacer el view que haga el filter por tags. dale para adelante @llazzaro

**Comment by mgaitan** [comment]
2015-03-15 11:46 GMT-03:00 Angel Velasquez <notifications@github.com>:

> Supongo que debería llevar a una pantalla de jobs que matcheen con el tag
> seleccionado, con lo cual el template estaría casi listo (sólo agregar los
> links), y habría que hacer el view que haga el filter por tags. dale para
> adelante @llazzaro <https://github.com/llazzaro>
>

exacto, debe mostrar la misma view  jobs_list pero limitado a los jobs que
tienen el/los tags seleccionados.




-- 
mgaitan.github.io
textosypretextos.com.ar <http://textosyprextextos.com.ar>

**Comment by llazzaro** [comment]
listo 
* ahora los tags son links.
* muestro los tags en la vista de jobs.

**Comment by llazzaro** [comment]
ahh quiza quieren cambiar los urls.
quedaron de esta forma:

trabajos/?tag=django

**Comment by angvp** [comment]
Por qué no trabajos/django ?

**Comment by llazzaro** [comment]
no me di cuenta.
ahí lo actualizo

**Comment by llazzaro** [comment]
listo ahora queda trabajos/django 
saludos, me fui a tomar una cerveza

**Comment by MissFilly** [comment]
Arreglé el form de la barra lateral para filtrar por tags. Volví a poner las URLs en forma `trabajos/?tag_django=1` (para incluir la tag) y `trabajos/?tag_django=2` (para excluir la tag) sólo para mantener la consistencia. Estaría bueno incluir múltiples tags prolijamente en la forma `trabajos/django`.
