### ISSUE TITLE
System Message: WARNING/2 (<string> line 396)

### ISSUE THREAD

**Issue by alener** [PyAr/pyarweb#237]
En http://beta.python.org.ar/wiki/Charlas hay varios de ese tipo de mensaje, luego aparecen varios
System Message: ERROR/3 (<string> line 14) id53
Por otro lado muchas de las charlas del comienzo no dicen en la página la fecha en que fueron dadas

**Comment by mgaitan** [comment]
@alener lo agreguemos a  #230
