### ISSUE TITLE
System Message: ERROR/3 (<string> line 96) y 98 en lista de correo

### ISSUE THREAD

**Issue by alener** [PyAr/pyarweb#239]
En http://beta.python.org.ar/lista  aparece:

System Message: ERROR/3 (<string> line 96)
Unexpected indentation.

hosting site:listas.python.org.ar/pipermail/pyar/ Donde le decimos a google que busque la palabra 'hosting' solamente
System Message: WARNING/2 (<string> line 98)
Block quote ends without a blank line; unexpected unindent.

**Comment by angvp** [comment]
Creo que esto ya fue arreglado hace tiempo
