### ISSUE TITLE
En wiki/noticias DseFChDXamYi

### ISSUE THREAD

**Issue by alener** [PyAr/pyarweb#240]
En http://beta.python.org.ar/wiki/Noticias aparece v6ARky <a href="http://gekteefghnuq.com/">gekteefghnuq</a>, [url=http://zksijuaooaad.com/]zksijuaooaad[/url], [link=http://fguknyeiedim.com/]fguknyeiedim[/link], http://qhhapjmqriqy.com/

Siempre usando Chromium

**Comment by mgaitan** [comment]
parece un bot de spam atacando Waliki. 

http://beta.python.org.ar/wiki/Noticias/history/

**Comment by mgaitan** [comment]
tener en cuenta que disminuirá/desaparecerá ya que ahora se exige login para la edicion

**Comment by cmdelatorre** [comment]
Supongo que este issue ya no es un problema.
