### ISSUE TITLE
WARNING/2 ERROR/3 en wiki/Eventos

### ISSUE THREAD

**Issue by alener** [PyAr/pyarweb#241]
En http://beta.python.org.ar/wiki/Eventos   :
hay varios link que van a paginas que aún no existen

System Message: WARNING/2 (<string> line 46) id5 id6 id8 id9

System Message: ERROR/3 (<string> line 11) id11
Undefined substitution referenced: ":-?".

System Message: ERROR/3 (<string> line 13) id13
Duplicate target name, cannot be used as a unique reference: "sprints".

System Message: ERROR/3 (<string> line 17) id15
Duplicate target name, cannot be used as a unique reference: "conferencias".

Siempre con el navegador Chromium

**Comment by mgaitan** [comment]
unificamos este problema en #230
