### ISSUE TITLE
deploy a beta con los ultimos cambios

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#244]
implementé los feeds rss (faltan los feeds de waliki mgaitan/waliki#32) y algunos cambios menores. 

podemos deployar a beta? @edvm :beers: :+1:

**Comment by edvm** [comment]
2015-03-14 0:16 GMT-03:00 Martín Gaitán <notifications@github.com>:

> implementé los feeds rss (faltan los feeds de waliki mgaitan/waliki#32
> <https://github.com/mgaitan/waliki/issues/32>) y algunos cambios menores.
>
> podemos deployar a beta? @edvm <https://github.com/edvm> [image: :beers:] [image:
> :+1:]
>
Deployando! Aunque rompimos el sitio: http://beta.python.org.ar/
Hoy me ponen a limpiar la casa, no lo voy a pode revisar hasta que termine
de ayudar con tareas del hogar. Martin, pasame tu pubkey por mail
y te agrego al authorized_keys

-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by angvp** [comment]
A mi me anda master bien en local, se corrieron las migraciones y se instaló todo lo que estaba en el requirements.txt ? ```pip install -Ur requirements.txt``` ? de hecho uno de los commits que metí fue el bump de la versión de django a 1.7.4 (en el otro PR bumpee a 1.7.6)

**Comment by edvm** [comment]
Perdon el top posting, Angel efectivamente hay un quilombo con las
migraciones arriba, yo dromedario la DB y arrancaría todo de 0, porque en
la base de beta venimos arrastrando un error desde el sprint hecho en
ralsina home, algo quedo mal en la base y pincha las migraciones,
@mgaitan,  Angel como lo ven?

**Comment by angvp** [comment]
me tirás el dump así lo levanto en local y veo si hay chance de sobrevivirlo?

**Comment by edvm** [comment]
Estoy en medio del campo sin compu llego en 2hs a casa aprox

**Comment by angvp** [comment]
Dale sin prisa no más estoy haciendo un poco de update en los tickets para ver si esta semana que estoy de vacaciones le meto unas horitas a lo que quedó pendiente por ahí

**Comment by edvm** [comment]
El 15 de marzo de 2015, 12:36, Angel Velasquez <notifications@github.com>
escribió:

> Dale sin prisa no más estoy haciendo un poco de update en los tickets para
> ver si esta semana que estoy de vacaciones le meto unas horitas a lo que
> quedó pendiente por ahí
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/244#issuecomment-81104863>.
>
Angel, Martin, no puedo dumpear la base :-(

www-pyar@python:~/pyarweb_beta/pyarweb$ PGPASSWORD="frulala" pg_dump -U
secret_usr beta_pyar > db.sql
pg_dump: [archivador (bd)] falló la conexión a la base de datos
«beta_pyar»: FATAL:  la autentificaci?n Peer fall? para el usuario
<<secret_usr>>

Llamamos a Nico a ver si nos puede dar una mano con esto?

-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by gilgamezh** [comment]
necesitan ayuda?

**Comment by mgaitan** [comment]
yes, please. haz tu magia.

**Comment by mgaitan** [comment]
ahi lo arregle, levantò http://beta.python.org.ar/

@angvp, @edvm el tema es que el cambio con los `Autoslug(unique=True... ` impide que se corran las migraciones si hay mas de un objeto (en nuestro caso era Jobs, pero probablemente suceda lo mismo con events). 

el atributo slug queda vacio por defecto y si hay mas de uno, revienta por no ser unique. 

Lo que hice fue dividir la migracion en 3 partes. 0003 agrega el slug con `unique=False`, 0004 es un datamigration que simplemente recorre todos los objetos y ejecuta `save()` y 0005 pone el `unique=True`

si tienen corridos en sus entornos las migraciones de jobs y les anda, pueden fakear 0004 y 0005 (o deshacer 0003, pullear y correr las todas)

**Comment by angvp** [comment]
Ok me fijo de agregar lo mismo para el pull request que tengo @mgaitan
