### ISSUE TITLE
NoReverseMatch at /

### ISSUE THREAD

**Issue by diegoduncan21** [PyAr/pyarweb#246]
solo al entrar al site.
![seleccion_001](https://cloud.githubusercontent.com/assets/1647454/6659857/dbbc021a-cb6c-11e4-8259-b9e5314c03b5.png)

**Comment by mgaitan** [comment]
si, tenemos un problema con las migraciones. lo arreglaremos en breve

On Sun, Mar 15, 2015 at 11:42 PM, Diego <notifications@github.com> wrote:

> solo al entrar al site.
> [image: seleccion_001]
> <https://cloud.githubusercontent.com/assets/1647454/6659857/dbbc021a-cb6c-11e4-8259-b9e5314c03b5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/246>.
>



-- 
mgaitan.github.io
textosypretextos.com.ar <http://textosyprextextos.com.ar>
