### ISSUE TITLE
AttributeError at /trabajo/rss

### ISSUE THREAD

**Issue by hobarrera** [PyAr/pyarweb#247]
`AttributeError at /trabajo/rss` al visitar http://beta.python.org.ar/trabajo/rss.

**Comment by hobarrera** [comment]
El error parece estar [acá](https://github.com/PyAr/pyarweb/blob/master/jobs/views.py#L28).

Creo que debería leer `job.title`.

**Comment by mgaitan** [comment]
arreglado en  f773187 . gracias!
