### ISSUE TITLE
Fixes breakpoint < 992px

### ISSUE THREAD

**Issue by pedromagnus** [PyAr/pyarweb#249]
En breakpoint < 992px:
1) el "Python powered" del footer cae abajo.
2) #main precisa padding-top de 20px.

**Comment by mgaitan** [comment]
qué lo arregle, qué lo arregle, :clap:  :dancers:

**Comment by pedromagnus** [comment]
PR https://github.com/PyAr/pyarweb/pull/250

**Comment by pedromagnus** [comment]
No SASS/LESS? 
No alfabetización de atributos? 
No usado de espacios en vez de tabs?
Esos estilos van a ser cada vez más dificil de mantener...

**Comment by mgaitan** [comment]
somos brutos peter, yo sabía que la estabamos cagando pero hasta ahi llegó mi osadía de conocimiento :-1:
