### ISSUE TITLE
Deploy a producción

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#251]
- [x] Bajar directorio `/data` para migrar via moin2git
- [x] Mover python.org.ar a old.python.org.ar
- [x] Backup de db actual (python manage.py dbbackup)
- [x] Mover beta.python.org.ar a python.org.ar
- [x] borrar datos de waliki (repo git `WALIKI_DATA` y todo lo que este en los modelos `waliki_*`)
- [x] subir resultado de migracion de wiki a github/pyar/wiki (via git)
- [x] subir resultado de migracion de attachment a la carpeta definida por `WALIKI_ATTACHMENTS_DIR` (default `media/waliki_attachments/`)
- [x] clonar github.com/pyar/wiki a la carpeta definida en settins.py `WALIKI_DATA` y correr `python manage.py sync_waliki`  
- [x] Dropear tablas de las apps newbie, faq, projects
- [x] correr el comando de cleanup de waliki `python manage.py moin_migration_cleanup`
- [x] limpiar/borrar contenidos de prueba y dejar los que sirven (noticias, eventos, trabajos)
- [x] configurar django-send_file para que use apache
- [x] Poner en solo lectura el MoinMoin de http://old.python.org.aar
- [x] probar! 
- [x] mandar mail avisando - mencionar a colaboradores (mencionar el diseño donado por MSA)

**Comment by edvm** [comment]
Bacapeando la base :)

**Comment by mgaitan** [comment]
para poner moinmoin en solo lectura ver https://moinmo.in/HelpOnAccessControlLists#Wiki_as_a_simple_CMS

```
acl_rights_default = u'Known:admin,read,write,delete,revert All:read,write'
acl_rights_before  = u'WikiAdmin,BigBoss:read,write,admin,delete,revert'
```

**Comment by mgaitan** [comment]
migración en curso :dancers: 

![captura de pantalla de 2015-03-28 11 14 04](https://cloud.githubusercontent.com/assets/2355719/6881383/df42abc2-d53b-11e4-800b-c6f2806a0d74.png)

**Comment by gilgamezh** [comment]
Yo me pongo a laburar con *Poner en solo lectura el MoinMoin*

**Comment by gilgamezh** [comment]
Felicitaciones!!!! :smiley: :tada:
