### ISSUE TITLE
crear una pagina de error custom

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#253]
que matchee un poco con el diseño del sitio. 

404 y 50x

ej feo: 
http://python.org.ar/lalala

**Comment by btenaglia** [comment]
@mgaitan voy a tomar este ticket. Te escribo de esta forma, porque no tengo manera de asignarmelo, quizás sean los permisos.

**Comment by btenaglia** [comment]
@mgaitan que les parece?
Ya las tengo listas, quedaron mucho mas presentables.

![500](https://cloud.githubusercontent.com/assets/2086311/7804027/27ef74a2-0333-11e5-8a67-946f1b0a7237.png)
![404](https://cloud.githubusercontent.com/assets/2086311/7804028/28004746-0333-11e5-85f5-5062fdb734c6.png)

**Comment by mgaitan** [comment]
:+1:  envias PR ?

**Comment by btenaglia** [comment]
@mgaitan este es el PR https://github.com/PyAr/pyarweb/pull/278

**Comment by angvp** [comment]
Una cosa de la página de 500 yo sacaría la parte de eventos + subscribite a la lista, pensá que si lo que se rompió fue la BD (o cambió el modelo de eventos y nadie tocó el nuevo queryset) cuando haga la consulta de próximos eventos va a estar roto, ergo no se va a mostrar nunca la página de 500 ;)

**Comment by btenaglia** [comment]
@angvp tenés razón, lo saqué y dejé solo el buscador (que esto si va a funcionar).
@mgaitan , el PR es https://github.com/PyAr/pyarweb/pull/279

**Comment by btenaglia** [comment]
![500](https://cloud.githubusercontent.com/assets/2086311/7827881/d3c3f8d2-0402-11e5-8e6d-6b55987a72ed.png)
