### ISSUE TITLE
Tipografía: Error en la sección de Trabajos

### ISSUE THREAD

**Issue by arianalidagarcia** [PyAr/pyarweb#255]
En el campo de descripción de la empresa que estás agregando al listado, te reconoce la tipografía pero no te deja cambiarla. Muchas gracias.
![test](https://cloud.githubusercontent.com/assets/5408370/6883043/382134c2-d57b-11e4-820c-41f4189f7f60.jpg)

**Comment by angvp** [comment]
No estamos usando ninguna tipografía distinta cuando lo mostramos en el template tampoco
