### ISSUE TITLE
Cambiar el asunto de emails de "beta.python.org.ar" a "python.org.ar"

### ISSUE THREAD

**Issue by ssebastianj** [PyAr/pyarweb#256]
Dado que estamos felizmente corriendo (:smiley:) en producción la versión *final* de PyAr habría que renombrar el texto **[beta.python.org.ar]** a **[python.org.ar]** que aparece como asunto en los emails.

![github_issue](https://cloud.githubusercontent.com/assets/309535/6883086/bd3bf178-d57c-11e4-9b8f-1d9790685fbb.png)

**Comment by gilgamezh** [comment]
Edité acá:

![screenshot from 2015-03-29 11 18 10](https://cloud.githubusercontent.com/assets/1496486/6885994/e7bb4c22-d604-11e4-9637-dda9dea22014.png)

Pero aparentemente no funcionó.

De dónde saco esa config?? cc @edvm @mgaitan

**Comment by mgaitan** [comment]
Ies rarísimo. encontré en la doc que se puede forzar con este setting

```
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[PyAR]"
```

http://django-allauth.readthedocs.org/en/latest/configuration.html

lo puse, pero no me da bola. Lo raro es que tiene algun sentido que no de bola porque tampoco le da bola al default, que el `name` del Site (que es lo que configuró nico).  

luego debuggeo mas

**Comment by edvm** [comment]
Stopearon/startearon todo? Borraron pyc?

2015-03-29 12:25 GMT-03:00 Martín Gaitán <notifications@github.com>:

> Ies rarísimo. encontré en la doc que se puede forzar con este setting
>
> ACCOUNT_EMAIL_SUBJECT_PREFIX = "[PyAR]"
>
> http://django-allauth.readthedocs.org/en/latest/configuration.html
>
> lo puse, pero no me da bola. Lo raro es que tiene algun sentido que no de
> bola porque tampoco le da bola al default, que el name del Site (que es
> lo que configuró nico).
>
> luego debuggeo mas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/256#issuecomment-87427300>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by ssebastianj** [comment]
Volví a probar restablecer mi contraseña hace unos minutos y esta vez muestra **[PyAr]** en el asunto (en corcondancia con el setting que comentó @mgaitan).  :+1: 

![github_issue](https://cloud.githubusercontent.com/assets/309535/6887804/7d755f7e-d640-11e4-8642-15c168e1e28e.png)

Queda como *pequeño* detalle estético el espacio faltante entre *[PyAr]* y *Correo para restablecer contraseña*.

**Comment by mgaitan** [comment]
great! @gilgamezh dejamos eso o lo pasamos a [python.org.ar]?

**Comment by gilgamezh** [comment]
@mgaitan  Me gusta PyAr. ahora le meto el espacio. :)  (este es el issue 265 XD lo notaron? :information_source:  )

**Comment by ssebastianj** [comment]
Compañeros, habiéndose solucionado el issue #256, hago el honor de cerrarlo. :fireworks:
