### ISSUE TITLE
deployar una instancia de sentry propia

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#258]
En #68 configuramos el servicio getsentry.com para tener reportes de las cosas que se rompen en producción (muchas, de paso :D). El servicio servicio solia tener una versión gratuita que ahora se convirtió en un trial de 15 dias (se nos acaba el 10/4) y luego hay que empezar a pagar. 

sin embargo el codigo sigue siendo libre (basado en django) y se puede instalar facilmente una instancia propia, por ejemplo en un subdominio tipo sentry.python.org.ar 

https://github.com/getsentry/sentry

analizar viabilidad (ver #257) e instalar si se puede.

**Comment by gilgamezh** [comment]
Esto me hace un poco de ruido debido a que tenemos bastante 'cargada' la VM de pyar.
Qué tan posible sería pedir un segundo VM a usla y separar algunas cosas en esa otra VM?

ping @facundobatista

**Comment by facundobatista** [comment]
Podemos pedir, y si no nos dan, comprar una.

Pero tenemos que estar seguros que la vamos a necesitar, o sea que no es al pedo...

Pregunta, ¿ese moin lo necesitamos para algo? Podríamos matarlo luego de, no sé, seis meses de tener los dos sitios en paralelo?

**Comment by gilgamezh** [comment]
Dejame conseguir datos para poder evaluar mejor. (estoy pidiendo info a Usla) 

Mi idea con Moin era meter algo (onda wget --spider ) que nos deje todo estático y guardarlo en old.python.org.ar

**Comment by mgaitan** [comment]
2015-04-13 10:29 GMT-03:00 Nicolás Demarchi <notifications@github.com>:

> Mi idea con Moin era meter algo (onda wget --spider ) que nos deje todo
> estático y guardarlo en old.python.org.ar
>
:+1:

-- 
mgaitan.github.io
textosypretextos.com.ar <http://textosyprextextos.com.ar>

**Comment by angvp** [comment]
@giglamezh podemos cerrar este? o que hacemos? :)

**Comment by gilgamezh** [comment]
![screenshot from 2016-05-07 12-53-25](https://cloud.githubusercontent.com/assets/1496486/15093084/bf9d8420-1452-11e6-8aae-c1078476c7e4.png)

Hoy tenemos esto ^^

Creo que nos sirve.

**Comment by angvp** [comment]
Ok cerramos el issue entonces cualquier cosa lo re abren :D
