### ISSUE TITLE
Configurar un cron para pushear la wiki a github

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#260]
Los cambios mezclados en github se sincronizan automaticamente via el webhook, pero hace falta sincronizar en sentido inverso. Por ejemplo con un cron cada dia, 

es `git push origin` desde el directorio definido en `WALIKI_DATA_DIR`

**Comment by gilgamezh** [comment]
listo! Agregué una "deploy key" con la llave del usuario de www-pyar y se hace push cada 10 minutos.
