### ISSUE TITLE
Instalar gettext

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#261]
Quiero poner algunos strings en español y no estoy seguro por qué no me da bola, pero cuando quiero correr `compilemessages` me tira este error: 

```
(pyarweb_venv) www-pyar@python:~/pyarweb/pyarweb$ python manage.py compilemessages -l es
CommandError: Can't find msgfmt. Make sure you have GNU gettext tools 0.15 or newer installed.
```

**Comment by gilgamezh** [comment]
Listo, pero me da un error que sospecho es de config:


```
(pyarweb_venv) www-pyar@python:~/pyarweb/pyarweb$ python manage.py compilemessages -l es
CommandError: This script should be run from the Django Git checkout or your project or app tree, or with the settings module specified.
```

**Comment by gilgamezh** [comment]
@mgaitan avisa cuando quieras probar esto.

**Comment by angvp** [comment]
ping @gilgamezh @mgaitan cerramos esto?

**Comment by mgaitan** [comment]
98% si, so, do it y reabrimos si hiciera falta.



On Thu, Oct 1, 2015 at 2:16 PM, Angel Velasquez <notifications@github.com>
wrote:

> ping @gilgamezh <https://github.com/gilgamezh> @mgaitan
> <https://github.com/mgaitan> cerramos esto?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/261#issuecomment-144790201>.
>



-- 
mgaitan.github.io
textosypretextos.com.ar
