### ISSUE TITLE
template para edicion no autorizada se ve feo

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#264]
cuando una regla ACL excluye a un usurio de editar una pagina, se ve un mensaje "no estás autorizado". Se ve feo: 

![captura de pantalla de 2015-04-07 16 48 28](https://cloud.githubusercontent.com/assets/2355719/7031998/00d123f6-dd46-11e4-9a45-c782b502a4bf.png)

**Comment by btenaglia** [comment]
@mgaitan , listo este ticket, el PR es https://github.com/PyAr/pyarweb/pull/280
![img](https://cloud.githubusercontent.com/assets/2086311/7876027/691c9c6a-059b-11e5-8ac9-167777c5db48.png)
