### ISSUE TITLE
User own pages should be allowed to be modified only for that user, *by default*

### ISSUE THREAD

**Issue by facundobatista** [PyAr/pyarweb#265]
So, if user FooBar register in the site, her /FooBar page should be only modified by herself, without the need to create any particular rule anywhere.

**Comment by mgaitan** [comment]
para implementar esto habria que hacer un receiver para la señal `allauth.account.signals.user_signed_up(request, user)` que cree una instancia de `waliki.models.ACLRule` con el permiso 'edit_page' para el usuario creado. 

http://django-allauth.readthedocs.org/en/latest/signals.html

ese mismo codigo se deberia ejecutar para todos los usuarios ya creados, implementando un datamigration 

por otro lado, para mí lo mejor es que todas las paginas de usuarios esten bajo un mismo namespace. 

por ejemplo `/miembros/MartinGaitan`

**Comment by facundobatista** [comment]
+1 a que estén todos bajo el mismo namespace... /user/FacundoBatista ?

**Comment by edvm** [comment]
2015-04-07 19:15 GMT-03:00 Facundo Batista <notifications@github.com>:

> +1 a que estén todos bajo el mismo namespace... /user/FacundoBatista ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/265#issuecomment-90747584>.
>
+1 a que sea /miembros/EmilianoDallaVerdeMarcozzi, lo comun es el ingles y
el
namespace '/user/' seria el adecuado, aunque en el sitio se hizo o se
hicieron tareas
en especifico para que las urls sean en espanol, so ... +1 a mantener el
espanol y
por ello +1 a /miembros.


-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by mgaitan** [comment]
:+1: 

Otro detalle

en algun lado del profile del user se deberia guardar el fk a "su pagina", cosa de poder asociar mas facilmente user con pagina, y poner links por ejemplo en desde el "autor" de una noticias, desde el historial de cambios de la wiki y demás

**Comment by facundobatista** [comment]
Y desde el nombre que te muestra cuando estés logueado...

**Comment by mgaitan** [comment]
ahi implementé una version basica. pueden revisar?

lo que no hace esto es redirigir las paginas de usuario que ya existen.  Por ejemplo mi pagina es `wiki/MartinGaitan` y hay que moverla manualmente (con el botón move que aparece en la pagina de edicion)  a `wiki/miembros/tin`

**Comment by cmdelatorre** [comment]
Entiendo que esto está resuelto. Si hay algo que falta, propongo que creen un issue específico.
