### ISSUE TITLE
planeta pyAr no actualiza desde 2015-03-23

### ISSUE THREAD

**Issue by ccanepa** [PyAr/pyarweb#270]
planeta pyAr no actualiza desde 2015-03-23 mientras que algunos blogs afiliados muestran actualizaciones posteriores, como el de humitos o facundobatista

**Comment by mgaitan** [comment]
@ralsina, esto lo hosteas vos, cierto? podés chusmear qué pasó? deberiamos pasarlo al server de pyar? 

@matagus hay alguna posibilidad que retomemos la integración de django-planet ?

**Comment by ralsina** [comment]
Yo dejé de administrarlo hace meses y meses ya que me dijeron que estaba en otro sistema, hecho por otra gente. Debe hacer seis meses que no lo miro más. Les pasé los datos de los feeds, etc, hace muchisimo.

Ahi lo destrabé, pero si lo tengo que seguir administrando avísenme, no quiero tener un servicio ahí, al pedo..

**Comment by ralsina** [comment]
Arreglado, se había quedado sin memoria el VPS.

**Comment by matagus** [comment]
@mgaitan dale, lo retomo este finde! tengo que ponerme al día que me perdí un poco
