### ISSUE TITLE
Agregar la posibilidad de revertir cambios

### ISSUE THREAD

**Issue by joac** [PyAr/pyarweb#271]
No encontré forma de volver a una versión anterior de una página de la wiki, es una funcionalidad necesaria, cuando uno hace cambios erróneos

**Comment by joac** [comment]
Mejor pongo el issue en waliki?

**Comment by mgaitan** [comment]
desde el historial o desde un diff podes acceder a una versión anterior y lo primero que sale allí es un botón que dice "restaurar esta versión". 

ejemplo 
  http://python.org.ar/wiki/Inicio/version/a68f0d2

**Comment by joac** [comment]
Lo busqué por todos lados y no lo encontré, gracias!
