### ISSUE TITLE
Listar los eventos en orden cronológico

### ISSUE THREAD

**Issue by humitos** [PyAr/pyarweb#275]
La página http://python.org.ar/eventos/ lista los eventos de la forma: "primero el último que se agregó" y estaría que bueno que muestre: "primero el próximo que viene en el tiempo (el que está más cerca)"

**Comment by btenaglia** [comment]
Hola @humitos @mgaitan  voy a hacer este ticket, es el primero que agarro, así que hoy comienzo a colaborar :).

**Comment by mgaitan** [comment]
fixed in #277
