### ISSUE TITLE
Link para crear evento visible para cualquier usuario

### ISSUE THREAD

**Issue by angvp** [PyAr/pyarweb#281]
Actualmente hay que estar registrado para poder ver el link de crear el evento, estaría bueno que no se necesite estar logueado y que aparezca el link y en el momento de darle link que aparezca el formulario de login

**Comment by mgaitan** [comment]
:+1:

**Comment by btenaglia** [comment]
@angvp @mgaitan puedo hacer esta tarea si quieren.
Me la asigno o alguno está laburando en esto??

**Comment by mgaitan** [comment]
avanti, mandalo!

On Mon, Jun 1, 2015 at 3:22 PM, Bruno M. Tenaglia <notifications@github.com>
wrote:

> @angvp <https://github.com/angvp> @mgaitan <https://github.com/mgaitan>
> puedo hacer esta tarea si quieren.
> Me la asigno o alguno está laburando en esto??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/281#issuecomment-107662887>.
>



-- 
mgaitan.github.io
textosypretextos.com.ar <http://textosyprextextos.com.ar>

**Comment by btenaglia** [comment]
@angvp @mgaitan buenísimo, en un rato ya envío pull request

**Comment by angvp** [comment]
:+1:

**Comment by btenaglia** [comment]
@angvp @mgaitan  acá les dejo el pull request https://github.com/PyAr/pyarweb/pull/284
