### ISSUE TITLE
Aplicación meet-up

### ISSUE THREAD

**Issue by angvp** [PyAr/pyarweb#282]
- [ ] Averiguar si meetup teine webooks o armar crontab
- [ ] Agregar modelo `EventGroup`
- [ ] Armar scripts que interactúen con la API de meetup

**Comment by gilgamezh** [comment]
Esto no es lo que ya armó @cmdelatorre ?

**Comment by cmdelatorre** [comment]
Esto no va a suceder. En el PyCamp 2018 empezamos a trabajar para incorporara [EventoL](http://eventol.github.io/eventoL/#/).
