### ISSUE TITLE
Crear un doc sobre "cómo colaborar"

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#293]
- [x]  explicar o brindar referencia sobre como crear un pull request y github (@edvm) 
- [x] calidad minima del código requerido (@angvp)

**Comment by edvm** [comment]
@mgaitan Voy a crear un branch 'develop' desde 'master', y hacer la documentación indicando forkear 'develop'. A master lo dejamos sin tocar, como 'estable'.

**Comment by edvm** [comment]
@mgaitan si no hay oposición, voy a borrar todos los otros branches, que son de issues-pirulo.

**Comment by edvm** [comment]
Doc de como hacer PR en Pull Request: https://github.com/PyAr/pyarweb/pull/295

**Comment by angvp** [comment]
Sorry @evdm me quise asignar yo pero te borró a vos, hagamos algo, cuando te acepten el primer item me asignas? igual ya empecé a laburar en esto.Sds.

**Comment by gilgamezh** [comment]
Me parece genial lo de usar master como `stable` yo podría buscar la manera de que cada vez que se hace merge en master ejecutemos un deploy en prod ;)

**Comment by edvm** [comment]
@angvp perfecto! :+1:

**Comment by angvp** [comment]
Listo ahí me lo asigné y sigo con esto

**Comment by angvp** [comment]
Podrían revisar #314 para poder cerrar este issue? :) si desean agregar algo ahora es el momento
