### ISSUE TITLE
Nueva app "adopta un newbie"

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#294]
Esta es una metaissue que linkeará a las tareas necesarias para implementar la nueva app. 

- [ ] Todos los interesados en colaborar configurarán su entorno de trabajo
- [x] Crear descripción de objetivos y funcionalidad requerida. Ver [propuesta](https://github.com/PyAr/pyarweb/wiki/Nueva-app-para-tutor%C3%ADas)
- [x] Revisar el código de implementación parcial legacy y fijarse qué sirve
- [x] Crear milestone e issues (lo más atómicas posible)

**Comment by alener** [comment]
Confirmo que ya tengo configurado mi entorno de trabajo, estoy listo para hacer los pull requests

**Comment by oscarvogel** [comment]
Buenos dias, ya tengo configurado mi entorno de trabajo luego de mucho pelear, paso algunos tips para los newbies como yo que quieran instalar el entorno de trabajo, perdon si por ahi algunas cosas son muy obvias pero las tuve que ir solucionando a medida que surgieron y para mi me costo.-

Lo instale en Ubuntu 14.04 y Python 3.4
Para instalar el entorno no es *** pyvenv3-3 pyarweb *** si no que es *** pyvenv-3.4 pyarweb ***
Para activar el entorno no debes estar dentro de la carperta pyarweb de lo contrario no toma correctamente el entorno (al menos me paso eso a mi)
Tambien para configurar el entorno debes tener en cuenta esto * http://askubuntu.com/questions/488529/pyvenv-3-4-error-returned-non-zero-exit-status-1 *

Creo que eso fue todo, cualquier cosita a disposicion.-

Saludos

**Comment by angvp** [comment]
No agregaría eso al README porque es muy del entorno que tenés y otras son muy obvias, pero lo que se me ocurre es que podemos hacer páginas del wiki donde diga como instalar en X distro, les parece bien?

**Comment by oscarvogel** [comment]
ok, lo elimino

**Comment by Nicogue** [comment]
Disculpen que me meta pero no creen que para agilizar aun mas el proceso se podrian armar los entornos dentro de vagrant + docker:
Linux host(vagrant(docker container))
MAC o windows (vagrant(docker host vm(docker container)))
de esta forma el usuario mas novato podria volcarse de lleno al desarrollo sin tener que andar preocupandose por la complejidad que conlleva setear un entorno desde 0.

Entiendo que el proceso en si es bastante enriquecedor y nos trae bastante aprendizaje sin embargo son muchos los que tiran la toalla cuando se ven impedidos por problemas de entorno.

Saludos.

**Comment by MMoresi** [comment]
Buenas, a mi me ya me aparecio el primer problema, quise levantar la vm y no podia era porque no estaba habilitada desde la bios, ahora pude, pero dentro de la maquina virtual, que no levanta entorno grafico, no puedo levantar los servicios! Saludos

**Comment by MMoresi** [comment]
Tengo un problema con la maquina virtual para levantar los servicios

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management

le estoy buscando la solucion googleando, acepto ayudas.
@mgaitan @alener @gilgamezh

**Comment by mgaitan** [comment]
Estimadísimos, escribí una propuesta general sobre cómo imagino la nueva app. Espero feedback, correcciónes, etc. si logramos un acuerdo podemos pasar en limpio y generar los issues concretos para implementar 

https://github.com/PyAr/pyarweb/wiki/Nueva-app-para-tutor%C3%ADas

**Comment by angvp** [comment]
Hey @oscarvogel no lo tomes a mal!, no lo dije para que hicieras eso!, nada que ver; te di una sugerencia de crear una página en el wiki con tu configuración por si alguien mas tiene ese entorno, mil disculpas si no se entendió de esa manera.

@MMoresi parece que te falta el paquete ```django-bootstrap3-datetimepicker``` contactame via IRC y te doy una mano con esto. 

Tratemos de dejar este issue para lo referido a la app de tutorías y en caso de errores de instalación o configuración usemos el resto de los recursos que tenemos (otros issues, etc).

**Comment by alener** [comment]
@mgaitan Yo a la app le agregaría una tercera pata "no vinculante": Empresas o trabajos que no consiguen regularmente que sus empleados o candidatos hagan  determinas tareas específicas o que les cuesta mucho podrían especificar cuales son esas tareas para que se puedan luego armar proyectos que cubran esos "agujeros". Creo que así podrían ganar más todos los jugadores

**Comment by gilgamezh** [comment]
@mgaitan me parece que esta joya tal como lo planteas. :smile: 

@alener -1 a que sea algo onda "pasantia" ya que el resultado del laburo puedeno ser en un proyecto "libre" en la mayoría de las veces y por otro lado creo que sería meternos en algo más complejo. 
En el caso de las "pasantias" me parece que se podría tomar como una oferta laboral. Que debería ademas ser retribuída de alguna manera.

saludos!

**Comment by alener** [comment]
@gilgamezh Sólo era una idea muy general para ver si era viable darle alguna forma.

**Comment by btenaglia** [comment]
@mgaitan @gilgamezh @alener @angvp @MMoresi  comencé a armar un diagrama para definir el modelo de datos, apenas lo tenga lo adjunto y si están de acuerdo empezamos a armar los modelos en django.

saludos!

**Comment by MissFilly** [comment]
Este es un borrador de models que armé para esta app hace un tiempo, por si sirve de algo:

    from django.contrib.sites.models import Site
    from django.conf import settings
    from django.core.validators import MaxValueValidator, MinValueValidator
    from django.utils.translation import ugettext as _
    from django.db import models
    from taggit.managers import TaggableManager
    
    
    class Project(models.Model):
        description = models.TextField(blank=True, verbose_name=_('Descripción'))
        title = models.CharField(max_length=250, verbose_name=_('Título'))
        link_repo = models.URLField(blank=True, verbose_name=_('URL del repositorio'))
        owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    
        tags = TaggableManager()
    
        def __str__(self):
            return self.title
    
    
    class Mentor(models.Model):
        user = models.OneToOneField(settings.AUTH_USER_MODEL)
        description = models.TextField(blank=True, null=True)
        available = models.BooleanField(default=True, verbose_name=_('Disponible'))
        start_date = models.DateTimeField(auto_now_add=True)
        notifications_ignored = models.PositiveIntegerField(default=0)
        slots = models.PositiveIntegerField(default=2, validators=[MaxValueValidator(4),
                                                                   MinValueValidator(1)])
        skills = TaggableManager()
    
        def __str__(self):
            return self.user.username
    
    
    class Apprentice(models.Model):
        STATUS_TRAINING = 'T'
        STATUS_IDLE = 'I'
        STATUS_WAITING = 'W'
    
        STATUS_CHOICES = (
            (STATUS_TRAINING, _('Entretenando')),
            (STATUS_IDLE, _('Inactivo')),
            (STATUS_WAITING, _('Buscando mentor')),
        )
        user = models.OneToOneField(settings.AUTH_USER_MODEL)
        description = models.TextField(blank=True, null=True, verbose_name=_('Descripción'))
        start_date = models.DateTimeField(auto_now_add=True)
        notifications_ignored = models.PositiveIntegerField(default=0)
        status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=STATUS_WAITING)
    
        interests = TaggableManager()
    
        def __str__(self):
            return self.user.username
    
    
    class Mentorship(models.Model):
        project = models.ForeignKey(Project, verbose_name=_('Proyecto'))
        mentor = models.ForeignKey(Mentor, verbose_name=_('Mentor'))
        apprentice = models.ForeignKey(Apprentice, verbose_name=_('Aprendiz'))
        start_date = models.DateTimeField(auto_now_add=True, verbose_name=_('Fecha de inicio'))
        end_date = models.DateTimeField(null=True, blank=True, verbose_name=_('Fecha de finalización'))
        blog_link = models.URLField(blank=True, verbose_name=_('URL del blog'))

No soy para nada partidaria de que los mentores y los mentados se llamen jedi y padawan, me parece que le quita demasiada seriedad y es poco intuitivo para quienes no hayan visto Star Wars, pero esa es mi opinión personal nomás.

**Comment by mgaitan** [comment]
Estimados, creé las tareas. ya se puede comenzar a laburar! 

https://github.com/PyAr/pyarweb/milestones/App%20%22Adopta%20un%20Newbie%22

recuerden avisar en un comentario si quieren agarrar una issue.

**Comment by mgaitan** [comment]
On Fri, Jun 19, 2015 at 8:22 PM, MissFilly <notifications@github.com> wrote:

> No soy para nada partidaria de que los mentores y los mentados se llamen
> jedi y padawan, me parece que le quita demasiada seriedad y es poco
> intuitivo para quienes no hayan visto Star Wars, pero esa es mi opinión
> personal nomás.


ok, no me opongo ( Yo soy uno de los no fanaticos de startwars). "mentado"
no existe en la acepción que pretendemos darle
http://lema.rae.es/drae/?val=mentado

las palabras correctas serian tutor y tutored (tutorado, en español)










-- 
mgaitan.github.io
textosypretextos.com.ar

**Comment by gilgamezh** [comment]
@mgaitan genial! gracias
