### ISSUE TITLE
Agregar Sitemap al sitio de PyAr

### ISSUE THREAD

**Issue by edvm** [PyAr/pyarweb#310]
Sirve para SEO y me lista todas las urls del sitio para poder scrappearlas y monitorizar  las paginas que tienen el string 'ERROR' o tienen links que no funcionan/están caídos.

**Comment by angvp** [comment]
Las urls del sitio que están rotas son solo las de las wikis? no es mejor agregar el comando en waliki? por otro lado si hace un sitemap, pero no para el comando ;)

**Comment by edvm** [comment]
El 7 de agosto de 2015, 15:46, Angel Velasquez <notifications@github.com>
escribió:

> Las urls del sitio que están rotas son solo las de las wikis? no es mejor
> agregar el comando en waliki? por otro lado si hace un sitemap, pero no
> para el comando ;)
>
> Angel, creo que sí, solo tenemos que considerar las urls/páginas de la
wiki.
Es buena idea agregarlo como comando de waliki.
Por último, no entendí "por otro lado si hace un sitemap, pero no para el
comando", como es esto?


-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by angvp** [comment]
Que el sitemap está bueno para que google, bing, yahoo!, duckduckgo, etc le peguen y nos indexen, pero para buscar páginas rotas es medio overkill. Por eso decía que si era para buscar las urls rotas es mas rápido y directo hacerlo en waliki :) justo @mgaitan estaba buscando colaboradores para waliki :D :tada:

**Comment by edvm** [comment]
Jajajaja ok ok voy a hacer el comando para waliki asi dumpea las urls :)

El 7 de agosto de 2015, 16:03, Angel Velasquez <notifications@github.com>
escribió:

> Que el sitemap está bueno para que google, bing, yahoo!, duckduckgo, etc
> le peguen y nos indexen, pero para buscar páginas rotas es medio overkill.
> Por eso decía que si era para buscar las urls rotas es mas rápido y directo
> hacerlo en waliki :) justo @mgaitan <https://github.com/mgaitan> estaba
> buscando colaboradores para waliki :D [image: :tada:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/310#issuecomment-128796360>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by edvm** [comment]
Cierro por inactivo (y porque no lo voy a hacer :P )
