### ISSUE TITLE
Templates para registrarse a la lista de correo en Inglés

### ISSUE THREAD

**Issue by humitos** [PyAr/pyarweb#311]
Hola a todos,

Si uno se suscribe a la lista mediante el sitio web: http://python.org.ar/lista/ los emails que le manda el servidor vienen en Inglés.

Más info: http://listas.python.org.ar/pipermail/pyar/2015-August/035683.html

"Parece" que el problema es cuando el sitio web hace un POST a mailman, ya que no está especificando el idioma del usuario final.

**Comment by mgaitan** [comment]
Hay que fijarse en el form oficial con que campo hidden y con que valor
define el idioma, y agregarlo a nuestro form

Aceptaremos el pull-request

**Comment by angvp** [comment]
Tenemos un voluntario para ver este issue (Tuxis en irc), si estás por acá presente, manifiéstate? ;).

**Comment by tuxis** [comment]
Aca estoy. yo me hago cargo este finde del issue

**Comment by gilgamezh** [comment]
avisen si hace falta ayuda con esto. Sospecho que hay que editar las settings de mailman

**Comment by tuxis** [comment]
Buenas, gente, disculpen la demora, che una pregunta en el formulario le ponemos directamente 'español' como opción, lo hacemos seleccionamos, o tenemos en la pagina algo que auto configura el idioma en base a la ip del usuario?

**Comment by tuxis** [comment]
Buenos dias, Gente probe enviarle a mailman el campo <input type="hidden" name="language" value="es">, que según lo que estuve estuve leyendo y lo que corrobore en otras instancias del mailman devuelve todo en español, acá me sigue enviando un email en ingles, alguien podría revisar la configuración de mailman y si tiene disponible el email en español?

**Comment by gilgamezh** [comment]
Por default en español. entiendo que no hay nada para soportar diferentes idiomas

**Comment by tuxis** [comment]
Estimados ya esta hecho el pull request, pero de todas formas para que el email llegue correctamente en español por lo que estuve revisando hay que cambiar en el mailman.

**Comment by angvp** [comment]
Cierro el issue ya que queda revisar la configuración de mailman
