### ISSUE TITLE
"Olvidé mi contraseña" debería recordarte el nombre de usuario

### ISSUE THREAD

**Issue by manuq** [PyAr/pyarweb#315]
Hoy quise editar la wiki y no pude ingresar. Intenté con "Olvidé mi contraseña" pero la nueva tampoco andaba. Hasta que me di cuenta que en realidad mi nombre de usuario era el que estaba mal.

Creo que el email que envía "Olvidé mi contraseña" tendría que recordarte el nombre de usuario. O debería haber otra forma de recuperar el nombre de usuario.

**Comment by mgaitan** [comment]
hola @manuq 
cual es el email que te llegó? el email de reset te debería decir

"En caso de haber olvidado su nombre de usuario, es XX"

acá el template
https://github.com/pennersr/django-allauth/blob/58f22fd6801a17177cb45f5de75b76c32ff231b2/allauth/templates/account/email/password_reset_key_message.txt#L8

chequeá y en cualquier caso reabrilo

**Comment by manuq** [comment]
Tenés razón @mgaitan ya lo decía el email.
