### ISSUE TITLE
En la pagina de info de listas los links a Pyar-bar y Pyar-Meta no estan funcionando

### ISSUE THREAD

**Issue by emilioramirez** [PyAr/pyarweb#318]
En la seccion de Listas [1], los links a pyar bar y pyar meta no estan funcionando, estimo que deberían apuntar a [3] y [2] respectivamente.

[1] http://python.org.ar/lista/
[2] http://listas.python.org.ar/listinfo/meta
[3] http://listas.python.org.ar/listinfo/pyar-bar

![pyar-meta-pyar-bar](https://cloud.githubusercontent.com/assets/1151097/9384590/e187d250-4727-11e5-9751-b217fa7a3df2.png)

**Comment by angvp** [comment]
Fixed, estaban mal los links de esa página, gacias por el reporte @emilioramirez
