### ISSUE TITLE
No se puede confirmar la suscripcion a la lista de correo pyar meta

### ISSUE THREAD

**Issue by emilioramirez** [PyAr/pyarweb#319]
No se puede suscribir a la lista meta.

1. Relleno el formulario de suscripción[2], me dice que me va a llegar un correo.
2. Me llega el correo con un link[1], cuando voy a link, el sitio me tira el siguiente error 404.

![404-pyar-suscripcion-pyarmeta](https://cloud.githubusercontent.com/assets/1151097/9384794/1ef37396-4729-11e5-8c49-824d11cff9cc.png)

[1] el link tiene la siguiente forma http://python.org.ar/mailman/confirm/meta/<hash de la suscripcion>
[2] http://listas.python.org.ar/listinfo/meta

**Comment by angvp** [comment]
Hmmm listas.python,org.ar es mailman por ahí el link de confirm debería ser tipo: listas.python.org.ar/mailman/confirm/meta ..

@gilgamezh en la configuración de la lista meta, uds tocaron algo para cambiar la url de confirm?, desconozco mailman pero esto no sería un bug de la web de pyar

**Comment by gilgamezh** [comment]
@angvp me parece que está mal la config de mailman. dejame mirarlo y les aviso!

**Comment by angvp** [comment]
Hola @gilgamezh revisaste esto?

**Comment by jcarizza** [comment]
Esto está funcionando.
