### ISSUE TITLE
Moderadores para ofertas de trabajo

### ISSUE THREAD

**Issue by angvp** [PyAr/pyarweb#323]
Revisando la página de trabajos me di cuenta de que hay gente que está haciendo cosas como esta: 

http://python.org.ar/trabajo/desarrolladores-javascript-ssr-sr/
http://python.org.ar/trabajo/buscamos-desarrolladores-frontend-angular/
http://python.org.ar/trabajo/analista-de-integracion/

Donde el lenguaje que se oferta no tiene NADA que ver con python en lo absoluto, si bien a alguien de la comunidad le puede interesar me parece que la idea de la cartelera de trabajo es que se postee trabajo donde python tenga algo que ver, y este no sería el caso, mi propuesta es, poder tener personas que moderen:

a) Que la oferta esté relacionada con python
b) Que esté bien escrita (no mas phyton por favor)
c) Que no sea un reposteo de la oferta laboral para estar siempre de primero -todo bien con el reposteo, pero hay consultoras que postean todos los días la misma oferta para aparecer de primeros-

Que les parece?

**Comment by btenaglia** [comment]
@angvp @mgaitan 
Está buena la idea, yo ya la había pensado.
Se me ocurre:

1- cuando alguien escribe una oferta de trabajo, la misma queda en estado 'PENDIENTE', le podriamos nostificar que está pendiente de aprobación.

2- se le envía un email a un moderador para que esté al tanto de esto.

3- el moderador revisa la OFERTA (podria ser desde el admin del sitio), si le parece bien, la APRUEBA y ahora si aparece publicada

Que les parece la idea??

**Comment by mgaitan** [comment]
+1.

complementariamente se deberia poder "convertirse" en moderador. cierto?





2015-09-21 14:22 GMT-03:00 Bruno M. Tenaglia <notifications@github.com>:

> @angvp <https://github.com/angvp> @mgaitan <https://github.com/mgaitan>
> Está buena la idea, yo ya la había pensado.
> Se me ocurre:
>
> 1- cuando alguien escribe una oferta de trabajo, la misma queda en estado
> 'PENDIENTE', le podriamos nostificar que está pendiente de aprobación.
>
> 2- se le envía un email a un moderador para que esté al tanto de esto.
>
> 3- el moderador revisa la OFERTA (podria ser desde el admin del sitio), si
> le parece bien, la APRUEBA y ahora si aparece publicada
>
> Que les parece la idea??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/323#issuecomment-142048426>.
>



-- 
mgaitan.github.io
textosypretextos.com.ar

**Comment by edvm** [comment]
En lugar de aprobar las ofertas de laburo, creo una mejor solucion lo
siguiente:
Meter un boton 'Borrar empleo' cual aparece solo para los usuarios qeu
tienen
cierto permiso u rol.
Me parece mas piola esto porque tenemos mas ofertas de Python que de
tecnologias que no corresponden. Ergo, si por default 'bloqueamos' las
propuestas
hasta que algun moderador las apruebe, vamos a terminar bloqueando
mayormente propuestas de trabajo validas. Esto hace mas lento el que la
propuesta este online. Ahora, si no bloqueamos nada, pero los usuarios
moderadores que tienen rol 'moderador' a acceder a la view de un job tienen
un
boton que les permite borrar el trabajo (al borrar es dirigido a un view
form donde
se le pregunta la razon por la que borra el empleo, y un checkbox que si es
marcado, se envia respuesta al author del empleo) me parece mas piola.
Saludos!

El 21 de septiembre de 2015, 14:33, Martín Gaitán <notifications@github.com>
escribió:

> +1.
>
> complementariamente se deberia poder "convertirse" en moderador. cierto?
>
>
>
>
>
> 2015-09-21 14:22 GMT-03:00 Bruno M. Tenaglia <notifications@github.com>:
>
> > @angvp <https://github.com/angvp> @mgaitan <https://github.com/mgaitan>
> > Está buena la idea, yo ya la había pensado.
> > Se me ocurre:
> >
> > 1- cuando alguien escribe una oferta de trabajo, la misma queda en estado
> > 'PENDIENTE', le podriamos nostificar que está pendiente de aprobación.
> >
> > 2- se le envía un email a un moderador para que esté al tanto de esto.
> >
> > 3- el moderador revisa la OFERTA (podria ser desde el admin del sitio),
> si
> > le parece bien, la APRUEBA y ahora si aparece publicada
> >
> > Que les parece la idea??
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PyAr/pyarweb/issues/323#issuecomment-142048426>.
> >
>
>
>
> --
> mgaitan.github.io
> textosypretextos.com.ar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/323#issuecomment-142051310>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by angvp** [comment]
Claro, mi idea es que los moderadores puedan editar / borrar ofertas y que les envíe un mail a los que publicaron esta oferta

**Comment by btenaglia** [comment]
@angvp  @mgaitan 
+1 a la propuesta de @edvm, tiene razón-
* Que por default todo se publique
* Que un moderador/admin pueda eliminarla
* Que el moderador/admin al momento de eliminar la oferta, escoja el motivo (puede ), ahi, el sistema enviará un email al dueño de la oferta explicando el motivo del por que su oferta fué dada de baja.

**Comment by mgaitan** [comment]
bien por mi, avanti

2015-09-21 15:37 GMT-03:00 Bruno M. Tenaglia <notifications@github.com>:

> @angvp <https://github.com/angvp> @mgaitan <https://github.com/mgaitan>
> +1 a la propuesta de @edvm <https://github.com/edvm>, tiene razón-
>
>    - Que por default todo se publique
>    - Que un moderador/admin pueda eliminarla
>    - Que el moderador/admin al momento de eliminar la oferta, escoja el
>    motivo (puede ), ahi, el sistema enviará un email al dueño de la oferta
>    explicando el motivo del por que su oferta fué dada de baja.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/323#issuecomment-142070479>.
>



-- 
mgaitan.github.io
textosypretextos.com.ar

**Comment by btenaglia** [comment]
@mgaitan @angvp @edvm les dejo el pull request de este ticket https://github.com/PyAr/pyarweb/pull/329

Cada vez se suman mas los anuncios de trabajo que nada tienen que ver con Python, estaría bueno ir poniendo esto en producción.
Hay un permiso especial que cree para los moderadores https://github.com/btenaglia/pyarweb/blob/issue_323/fixtures/permission.json

Saludos a todos!!

**Comment by dmalisani** [comment]
Y si se pone algo como "Python Friendly" si tiene "algo" de python pero no es "exclusivamente" python? (para no tener que borrarlo si hay dudas)  por ejemplo
------
Necesito Front End developer... (php... y todo eso otro... "puag....")
Deseable. Django Framework
-------

**Comment by angvp** [comment]
Deseable no quiere decir que va a trabajar con eso, si es saberlo para tener que trabajar con otra cosa que no es python; para mi ya está en el borde del spam

**Comment by dmalisani** [comment]
Exactamente a eso me refería "está en el borde" ¿de que lado? ;)

**Comment by angvp** [comment]
Yo particularmente diría que no entra, si se flexibiliza mucho esto, terminan cayendo ofertas de las que te piden 10 lenguajes (entre ellas python) pero luego terminas laburando con bash .. y sería un recurso que usarían muchos recruiters para publicar sus ofertas, PERO no sé que tantas personas pueden contratar con esa metodología, yo particularmente no me gasto en aplicar a sitios así, pero ese soy yo y IMO siento que ofertas como esa hacen ruido entre el resto de las ofertas. 

Ahora si el puesto requiere que se escriban pocas líneas python (menos de un 5%~) y mas de otro lenguaje (95%~), ponele que podría entender que esté listada ahí.

Personalmente creo que esto es una discusión mas filosófica de las personas que van a moderar los puestos, hacer una funcionalidad mas para marcar "casos bordes" y que salga en el anuncio algo tipo "Alerta esta oferta de trabajo puede que no sea 100% python" me parecería bien, pero me parece que quedaría para la próxima versión de este módulo, luego de saber de la voz de los moderadores si realmente vale la pena desarrollar esa feature.

Sds.

**Comment by btenaglia** [comment]
Yo diría que por el momento esas cosas quedarían en manos del moderador, por ahora.
Opino que por ahora podríamos ir haciendo CR de este pull request y lanzarlo así, a modo que no metan mas SPAM.
Luego podríamos ir haciendo nuevo features.
Gracias!

**Comment by angvp** [comment]
:+1: dejame que lo chequee mejor, y le arme un mail a @gilgamezh de los pasos que tenemos que hacer en producción para este deploy

**Comment by angvp** [comment]
El deploy de esta feature ya está.. quedó un error:

http://linkode.org/z9iEMUILcG0qRQ7ohhVQL6

Ahora mismo tengo que salir, pero luego envío el parche, o si alguien quiere adelantarse y hacer el PR (directo a master ya que es un hotfix), perfecto. Sds.
