### ISSUE TITLE
Eliminar Oferta de Trabjo - Bug al hacer click en el botón Cancelar

### ISSUE THREAD

**Issue by btenaglia** [PyAr/pyarweb#324]
Acción: Eliminar Oferta de Trabajo
En el formulario para eliminar una oferta de trabajo, si se hace click en Cancelar, se produce un error.
El bug se produce porque redirecciona a una url que no existe, ya que se le pasa como parámetro el id y no el slug.

**Comment by btenaglia** [comment]
@mgaitan @MissFilly yo lo soluciono

**Comment by angvp** [comment]
Ahora reviso el pr Bruno

**Comment by btenaglia** [comment]
@angvp @mgaitan este es el PR, lo hice contra Develop
https://github.com/PyAr/pyarweb/pull/327

**Comment by angvp** [comment]
Listo, ya entró en develop. ¡Mil gracias @btenaglia!
