### ISSUE TITLE
el iframe de chat deberia ser maximizable

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#328]
que tenga un botón que via maximice el tamaño del iframe a todo el viewport. 

No debe ser un link con la misma url que el iframe porque si el usuario ya está logueado, deberia volver a loguearse e ingresar el canal en la nueva ventana. 
![captura de pantalla de 2015-10-08 11 40 55](https://cloud.githubusercontent.com/assets/2355719/10369686/e9d503e6-6db1-11e5-8073-2e5a0e5dda66.png)

**Comment by edvm** [comment]
@mgaitan cierro este issue por 'viejo', si lo ves con ganas de encararlo, re-open it! :) :+1:
