### ISSUE TITLE
Error al grabar página en la wiki

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/pyarweb#335]
varios usuarios reportaron en la lista que no pueden grabar cambios en la wiki

> On 11/25/2015 09:24 AM, Marcos Dione wrote:
> On Wed, Nov 25, 2015 at 08:59:25AM -0300, Juanjo Conti wrote:
> 
> > Hola, acabo de crearme el usuario jjconti y al intentar modificar esta
> > página http://python.org.ar/wiki/Charlas/ obtengo "Server Error
> > Lo sentimos, pero el servidor encontró un error al procesar su solicitud."
> 
> ```
>  +1
> ```

**Comment by mgaitan** [comment]
lo veo por la tarde

**Comment by facundobatista** [comment]
Me pasó hoy...
