### ISSUE TITLE
Sección Trabajo - Ordenar Etiquetas

### ISSUE THREAD

**Issue by btenaglia** [PyAr/pyarweb#341]
Hola @mgaitan @angvp @gilgamezh 
Una de las cosas que estoy viendo es que las etiquetas en la sección Trabajos está creciendo muchísimo, cada vez hay mas.
Ya van varias veces que quiero buscar por una en particular, y encontrarlo dentro de las cientas que hay es complicado.

Propongo:
- Mostrarlas en orden alfabético

Que opinan? 
Les parece bien la idea?

Si quieren encaro esto.

**Comment by angvp** [comment]
Por mi está bien, aunque cada tanto estaría bueno pegar una limpieza de tags que estén duplicados tipo java script y javascript .. unirlos en solo 1 .. pero eso es otro tema, y otro issue, :+1: por mi @btenaglia

**Comment by btenaglia** [comment]
@angvp joya, yo lo encaro.

**Comment by gilgamezh** [comment]
:+1: 

FTR: algo que me parece estaría genial es postear en una cuenta de twiter @pyar_trabajos con un moderador que vaya aprobando. ;)

**Comment by jcarizza** [comment]
@gilgamezh eso se puede hacer con [twitterfeed.com](http://twitterfeed.com)

 Conecte el RSS de [trabajos](http://www.python.org.ar/trabajo/rss) con [twitterfeed.com](http://twitterfeed.com) y cree una cuenta de twitter [@pyjob01](https://twitter.com/pyjob01) para mostrar las entradas.

Quien maneje las redes sociales puede hacerlo y agregar Facebook, Linkedin y Twitter.

**Comment by mgaitan** [comment]
otra posibilidad es https://ifttt.com

**Comment by edvm** [comment]
Cierro por duplicado con https://github.com/PyAr/pyarweb/issues/407
