### ISSUE TITLE
App pyconar

### ISSUE THREAD

**Issue by edvm** [PyAr/pyarweb#342]
Crear una aplicacion 'pyconar' que facilite la gestion de las conferencias nacionales de python en Argentina PyConAr. A breve la misma deberia permitir:
- Gestionar varias pycones, ej: /pyconar/2015, /pyconar/2016, donde el anio es el 'slug'.
- Gestionar el dinero que entra y el que se gasta
- Tener un calendar donde se muestran las charlas de la conferencia
- Permitir tener un 'landing page' para la edicion de la conferencia, al estilo PyConAr 2015 Mendoza:
  http://ar.pycon.org/ 
  El 'landing page' debe cargar un css desde la base de datos (u otro lado) que permita hacer modificaciones en el estilo de la landing page.
- (opcional) Gestionar permisos/roles sobre la informacion que se maneja en la app pyconar. El tesorero accede a toda la data de manejo de dinero, el coordinador general accede a toda la data, el 'community manager' accede a la data de los sponsors, etc.
- Integracion con mandrill para envio de emails (12000 emails mensuales gratuitos, tiene que alcanzar)
- Form para submitear charla
- Workflow para aprobar/no aprobar charlas (por el coordinador de charlas). Sistema de votos (un positive integer field de votos) donde el comite que puede votar hace +1 en las charlas.

Agreguen a este issue mas features para definir la app por favor :). Por cada feature, crear 
un issue en el milestone 'pyconar':
https://github.com/PyAr/pyarweb/milestones/pyconar
Tenemos tiempo hasta el 30 de septiembre, a darle masa!

**Comment by gilgamezh** [comment]
@edvm yo entendí que querían armar una app para meetup (?)

**Comment by edvm** [comment]
Yo quiero armar una app para la web de PyAr :)

2016-02-17 11:17 GMT-03:00 Nicolás Demarchi <notifications@github.com>:

> @edvm <https://github.com/edvm> yo entendí que querían armar una app para
> meetup (?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/342#issuecomment-185223867>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by gilgamezh** [comment]
yo dije que no hagamos eso? entendiste mal.

BTW: creo que la propuesta original fue `app para eventos de python`

http://listas.python.org.ar/pipermail/pyar/2016-February/037674.html

**Comment by mgaitan** [comment]
symposion es una app para gestion de conferencias que hace la gente de
Pinax y es la que se usó en las pycons de us.

la experencia de @d3f0 con las scipycon fue mala, pero habria que ver en
qué estado esta ahora y/o que se puede aprovechar

https://github.com/pinax/pinax-project-symposion
https://github.com/pinax/symposion




On Wed, Feb 17, 2016 at 11:25 AM, Nicolás Demarchi <notifications@github.com
> wrote:

> yo dije que no hagamos eso? entendiste mal.
>
> BTW: creo que la propuesta original fue app para eventos de python
>
> http://listas.python.org.ar/pipermail/pyar/2016-February/037674.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/342#issuecomment-185227650>.
>



-- 
mgaitan.github.io
textosypretextos.com.ar

**Comment by edvm** [comment]
@gilgamezh Nico, que entendi mal? En mi respuesta no dije otra cosa que "Yo
quiero armar una app para la web de PyAr :)". No hago referencia a algo que
hayas dicho, por lo que no entiendo tu pregunta: "yo dije que no hagamos
eso?".
Abrazo,
Emi.

2016-02-17 11:25 GMT-03:00 Nicolás Demarchi <notifications@github.com>:

> yo dije que no hagamos eso? entendiste mal.
>
> BTW: creo que la propuesta original fue app para eventos de python
>
> http://listas.python.org.ar/pipermail/pyar/2016-February/037674.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/342#issuecomment-185227650>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by edvm** [comment]
@mgaitan genial! @d3f0 en que cosas resulto floja la app de pinax symposion?

**Comment by matagus** [comment]
Además de symposium, está [conference](https://github.com/pythonitalia/conference) (que es la que usa Python Italia y que están metiendole laburo ahora). Los [models](https://github.com/pythonitalia/conference/blob/master/conference/models.py) -para empezar- pintan bastante completos. No digo que sea mejor que symposium, solo la tiro para chequearla ;)

btw muy buena la idea!

**Comment by edvm** [comment]
Otra app, utilizada en los flisol de .ar, EventoL:
http://listas.python.org.ar/pipermail/pyar/2016-February/037686.html

**Comment by ihuro** [comment]
Como afecta esto a las issues  #114 y #282 ? habría que cerrarlas?

**Comment by edvm** [comment]
El 23 de febrero de 2016, 14:09, César Roldán <notifications@github.com>
escribió:

> Como afecta esto a las issues #114
> <https://github.com/PyAr/pyarweb/issues/114> y #282
> <https://github.com/PyAr/pyarweb/issues/282> ? habría que cerrarlas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/342#issuecomment-187794845>.
>
Son tareas diferentes, la aplicacion 'pyconar' tiene que resolver cosas
propias que
se dan en la organizacion de una PyCon, mientras que el MeetUp tiene otros
requerimientos.
Saludos!


-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by edvm** [comment]
Cierro issue, delirio del 2016 :)
