### ISSUE TITLE
agregar slugs en urls de detalle

### ISSUE THREAD

**Issue by mgaitan** [PyAr/pyarweb#346]
Las url con slug son mucho más semánticas, mejor posicionadas en los buscadores y más facil de recordar/buscar en historial por los humanos. 

el slug se debe calcular solo a partir del titulo o el campo más caracteristico. Si es editable, mejor. 

aplicaria a noticias, eventos y jobs. 

Podemos seguir basandonos en el id pero agregar el slug al permalin

```
http://www.python.org.ar/eventos/21/ 
http://www.python.org.ar/eventos/21/cordoba-python-meetup-marzo
```

o reemplazar el lookup

```
http://www.python.org.ar/eventos/cordoba-python-meetup-marzo
```

Cualquiera sea la decisión, las urls anteriores deben funcionar y redirigir

**Comment by angvp** [comment]
Había un issue anterior relacionado con esto.. que estuvo parcialmente implementado, y luego lo olvidé completamente de arreglarlo +  subir el pr .. este fin lo retomo

**Comment by angvp** [comment]
Resulta que ESTE FIN es hoy, me asigno esto y lo hago hoy en el sprint, woot :)

**Comment by edvm** [comment]
@angvp queres aun meterle a esto? :)

**Comment by angvp** [comment]
Oh, colgué con esto por alguna razón, pero not really, no estoy teniendo mucho tiempo y no vengo haciendo mucho python últimamente :( .. así que mejor que lo dejen para alguien nuevo y con hambre de contribución :D

**Comment by edvm** [comment]
Nou problem @angvp ! :)

**Comment by sofide** [comment]
@edvm  lo vamos a ver ahora con @eduzen

**Comment by eduzen** [comment]
@edvm podrías asignarmelo?
