### ISSUE TITLE
Dockerizar el proyecto

### ISSUE THREAD

**Issue by edvm** [PyAr/pyarweb#354]
A fines de que sea mas sencillo arrancar a trabajar/comenzar a programar en el proyecto, crear un Dockerfile para construir una imagen que permita tener containers que simplifiquen el desarrollo, por ej:
1- Que ya instale las dependencias necesarias
2- Venga con un interprete de Python 3 con e instale los requirements
3- etc...

**Comment by angvp** [comment]
@edvm Emi! si podés armalo con un microcontainer https://github.com/iron-io/dockers/blob/master/python/python3/Dockerfile ... Acá tenés un Dockerfile para python3

**Comment by edvm** [comment]
Ando en eso, ya funcionando, ahora estoy escribiendo una tool simple en py3
que tira comandos de docker :)

2016-05-07 12:52 GMT-03:00 Angel Velasquez <notifications@github.com>:

> @edvm <https://github.com/edvm> Emi! si podés armalo con un
> microcontainer
> https://github.com/iron-io/dockers/blob/master/python/python3/Dockerfile
> ... Acá tenés un Dockerfile para python3
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/PyAr/pyarweb/issues/354#issuecomment-217646469>
>



-- 
Find me at http://edvm.chiba.ga <https://github.com/edvm>

<edvm@python.org.ar>

**Comment by mgaitan** [comment]
Fixed in #360
