### ISSUE TITLE
Reparar el proyecto

### ISSUE THREAD

**Issue by edvm** [PyAr/pyarweb#366]
Venimos desde hace tiempo sin poder avanzar en actualizar prod. Hoy hicimos un poco de research y pudimos definir lo siguiente:
Lo que esta andando en producción ahora mismo esta taggeado como: 
`prod-works-dd-mm-yyyy`
Al día de la fecha el tag que esta funcionando en prod es:
[https://github.com/PyAr/pyarweb/releases/tag/prod-works-26-11-2016](url)

Propongo revisar el branch 'develop', clasificar los commits por 'features', e ir mergeandolos a 'master' uno a uno, viendo que la cosa funcione. Por tirar un ejemplo, se podría hacer solo un sprint para mergear y hacer funcionar los cambios que hizo @cmdelatorre en el PR #357 , integrarlos a 'master' y ver que todo funcione. Una vez eso funciona, taggear nueva version  y deployar en prod.

Ideas y ayuda son bienvenidos!

**Comment by cmdelatorre** [comment]
Propongo resolver esto durante el PyCamp. Aunque no sé quién está al tanto de los problemas que hacen falta destrabar para sacar la cosa andando.

**Comment by cmdelatorre** [comment]
@edvm te extrañamos.
