### ISSUE TITLE
Missing local_settings.py instructions

### ISSUE THREAD

**Issue by lecovi** [PyAr/pyarweb#374]
There is no `local_settings.py` instructions in contributing

**Comment by angvp** [comment]
Esto no debería estar en CONTRIBUTING.md pero sí en el README.md o en las instrucciones de instalación

**Comment by cmdelatorre** [comment]
Puse una oración al respecto acá: https://github.com/PyAr/pyarweb/wiki/Instalaci%C3%B3n-manual
