### ISSUE TITLE
Mejorar dockerización del proyecto

### ISSUE THREAD

**Issue by cmdelatorre** [PyAr/pyarweb#382]
- [x] Actualizar la documentación correspondiente (la [wiki](../wiki/Instalacion-con-Docker) por lo pronto) 
- [x] Tener una imagen pública en docker hub: para poder pullear directamente una imágen con todo el proyecto en marcha y no tener que buildear uno mismo.
- [x] Agregar un Makefile (o equivalente) con los comandos de `docker-compose` más comunes: `start`, `stop`, `test`, `djshell`, `reset_db`, etc

**Comment by gilgamezh** [comment]
todo listo!
