### ISSUE TITLE
Wrong link in the confirmation email

### ISSUE THREAD

**Issue by laureanoSilva** [PyAr/pyarweb#383]
The link sent with the confirmation email is wrong; it points to example.com/....

**Comment by jcarizza** [comment]
it's necessary to set the EMAIL_CONFIRM_LA_DOMAIN in the settings according to https://github.com/vinta/django-email-confirm-la/blob/master/email_confirm_la/conf.py

**Comment by edvm** [comment]
Me registre en la app y no me llego mail de confirmacion. @laureanoSilva @jcarizza donde mas ocurre esto de que no llega el mail?

**Comment by mikiangel10** [comment]
@laureanoSilva  en el mail de activación de la cuenta te llegó mal el link@ podes fijarte si sigue habiendo problema?

**Comment by edvm** [comment]
@mikiangel10 @laureanoSilva me paso esto por email, parece que el error esta relacionado con la app de eventos:
```
El día 26 de Marzo de 2017 a las 19:20, a través del sitio de PyAr, ha solicitado inscribirse al evento Deploy A Produccion .

Para verificar la inscripción haga click en el siguiente link:

http://example.com/email_confirmation/key/222ad6a1a5d74656b40c06b5c76066e1/

Este link será válido durante los próximos 7 días.

Los datos de inscripción provistos fueron:

Nombre: luri
Email: laureano.bara@gmail.com
Si ud. no solicitó la inscripción puede desestimar este mensaje.
```

Espero estos datos te den una pista de por donde buscar :)

**Comment by cmdelatorre** [comment]
@mikiangel10 ¿no hay PR para esto?

**Comment by mikiangel10** [comment]
Perdón. No me puedo conectar ahora, pero hice un pr. Si no me equivoco. Sino en mi repo esta el fork con el commit listo. En cuanto pueda lo hago.

**Comment by edvm** [comment]
@mikiangel10 pudiste crear el PR? :)

**Comment by mikiangel10** [comment]
Ahora hice el pr. Perdón. Es que lo habia hecho en mi fork. Ahora entendí el mecanismo. Fíjate y decime cualquier cosa

**Comment by edvm** [comment]
@mikiangel10 perfect! revise tu PR (https://github.com/PyAr/pyarweb/pull/425) y pedi corregir un error de flake8 (de `'estilos'`). Ni bien actualices el PR (comiteas en tu branch el fix y el PR se actualiza solo), lo vuelvo a revisar asi ya lo mergeo :+1:  :D

**Comment by FedericoJurio** [comment]
@edvm Estaba viendo el backlog y este issue está resuelto y mergeado hace un par de meses. Sigue abierto por algún motivo en particular?
