### ISSUE TITLE
Error al registrar usuario nuevo

### ISSUE THREAD

**Issue by cmdelatorre** [PyAr/pyarweb#394]
Este problema fue reportado a lista de mails dos veces: 

- primero @facundobatista el [4 de Abril de 2017](http://listas.python.org.ar/pipermail/pyar/2017-April/041136.html)
- Luego Miguel Martinez el [7 de Abirl de 2017](http://listas.python.org.ar/pipermail/pyar/2017-April/041148.html)

El error en cuestión es:

> IntegrityError at /accounts/signup/
> null value in column "last_login" violates not-null constraint
> DETAIL:  Failing row contains (...

Esto sucede por problemas de migraciones con `django.contrib.auth`. 

Mi hipótesis es:

1. Intentando normalizar el deploy en producción durante el PyCamp 2017, entre otras cosas, vaciamos la tabla de migraciones de Django. 
2. Luego corrimos un `migrate --fake` lo que (aparentemente) solucionaba los problemas que teníamos en ese momento.
3. Luego `contentypes` nos mordió y ahí tuvimos que volver a correr las migraciones de esta app, solucionando el problema.
4. Esto último es lo que nos está pasando con `auth`.

Entonces, para solucionarlo hay que resetear las migraciones de `auth` en el server de producción. Haciendo esto en un entorno de prueba soluciona el problema:

```
$ python manage.py migrate auth 0001
Operations to perform:
  Target specific migration: 0001_initial, from auth
Running migrations:
  Rendering model states... DONE
  Unapplying auth.0006_require_contenttypes_0002... OK
  Unapplying auth.0005_alter_user_last_login_null... OK
  Unapplying auth.0004_alter_user_username_opts... OK
  Unapplying auth.0003_alter_user_email_max_length... OK
  Unapplying auth.0002_alter_permission_name_max_length... OK
$ python manage.py migrate auth     
Operations to perform:
  Apply all migrations: auth
Running migrations:
  Rendering model states... DONE
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
```

Cabe mencionar que ya @arielrossanigo vaticinó que esto iba a suceder. Además es probable que vuelva a pasar con otras contrib apps.

**Comment by gilgamezh** [comment]
corrí los comandos en producción, probé de registrar un usuario y funcionó oka.

**Comment by gilgamezh** [comment]
@cmdelatorre gracias!
