### ISSUE TITLE
Agregar campo "género" al form de inscripción a eventos

### ISSUE THREAD

**Issue by cmdelatorre** [PyAr/pyarweb#395]
Esto surge a partir del comentario de @mgaitan: https://github.com/PyAr/pyarweb/pull/357#discussion_r79693120

La idea es tener este campo para poder (eventualmente) tener estadísticas asociadas a la cuestión de genéro.

**Comment by gilgamezh** [comment]
Esta mergeado en dev y deployado en Beta. 
Yo creo que está para pasarlo a master. Con el +1 de alguien lo hago. 

NOTA: creo que está bueno empezar a usar el criterio de probar en beta y con el mismo criterio de un MR (+1 de alguien que hace review) se hace el deploy a produccion

**Comment by cmdelatorre** [comment]
Me parece bien. Podríamos agreagar eso en la parte de https://github.com/PyAr/pyarweb/wiki/Contribuyendo-con-PyArWeb
o en 
https://github.com/PyAr/pyarweb/wiki/Manual-b%C3%A1sico-de-supervivencia-para-colaborar-con-el-sitio-de-PyAr

**Comment by eamanu** [comment]
Probé y funciona lo del génenero.

Coincido con @gilgamezh sería interesate el criterio del beta, para luego hacer le deploy.

**Comment by edvm** [comment]
Mergeado y pusheado a `dev`: https://github.com/PyAr/pyarweb/pull/396
Cierro issue :+1:
