### ISSUE TITLE
Unificar Noticias, Trabajos y Eventos en la home page

### ISSUE THREAD

**Issue by cmdelatorre** [PyAr/pyarweb#397]
La sección de noticias no tiene mucho movimiento. Más se mueven las secciones de _Trabajos_ y _Eventos_.

En la página principal de PyAr el primer widget dinámico que aparece es justamente _Últimas noticias_ y después de ese aparece _Últimos avisos de trabajo publicados_.

Propongo unificarlos en un único panel de "_Últimas novedades_" o algo así, que incluya referencias a todos estos modelos juntos y quizá los eventos pasados.

**Comment by cmdelatorre** [comment]
Hay una implementación de esto, para ver cómo queda, en #398

**Comment by edvm** [comment]
Mergeado a `dev`: https://github.com/PyAr/pyarweb/pull/398
Muchas gracias @cmdelatorre !
