### ISSUE TITLE
enhancement: Traducción de los PEP

### ISSUE THREAD

**Issue by eamanu** [PyAr/pyarweb#400]
Sería interesante tener en la página de pyar, la lista de los PEP, y en los posible traducidos al español

Que les parece?

**Comment by cmdelatorre** [comment]
La idea me parece buena, aunque el esfuerzo sea grande.
Calculo que se puede ir haciendo directamente en la Wiki ¿cierto?

**Comment by eamanu** [comment]
Me parece bien en la Wiki

**Comment by eamanu** [comment]
Tengo que mandar un mensaje que se indica en `http://www.python.org.ar/wiki/ContribuyendoAlWiki` a pyar@python.org.ar?

**Comment by cmdelatorre** [comment]
Parece que no. ¿No te deja crear una página?
Estas cosas por ahí es más fluído que lo trates en el canal de IRC.

**Comment by edvm** [comment]
@eamanu deberías poder registrarte en el sitio, y estando logueado, crear contenido en el wiki. Estos pasos te funcionan? :)

**Comment by edvm** [comment]
Estaría bueno tomar esta iniciativa como un proyecto de traducción, cierro el issue por no se actualizado hace tiempo.
