### ISSUE TITLE
Error: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by eamanu** [PyAr/pyarweb#401]
Hola a todos, 

estoy tratando de instalar el pyarweb, pero me salta este error

fe_sendauth: no password supplied

Seguí todos los pasos.

**Comment by cmdelatorre** [comment]
Por favor, pegá un stack trace más completo. Idealmente, debería incluir desde el comando que ejecutaste hasta el final del trace.

**Comment by eamanu** [comment]
Lo solucioné. Era un conflicto de Django tratando de acceder a postgres con una pass diff. 

Soy nuevo.

Gracias
