### ISSUE TITLE
Servidor caido

### ISSUE THREAD

**Issue by eamanu** [PyAr/pyarweb#404]
¿El servidor se encuentra caído? ¿El mailing list tampoco anda? Por ese motivo uso este medio.

**Comment by gilgamezh** [comment]
Hola gracias por avisar. 

Hay problemas en USLA (donde están hosteados los equipos)

**Comment by eamanu** [comment]
Recien veo .. es el issue #404

**Comment by mgaitan** [comment]
Fixed http://listas.python.org.ar/pipermail/pyar/2017-May/041242.html
