### ISSUE TITLE
Wiki ORM - System Message: WARNING/2 (<string> line 21) id2

### ISSUE THREAD

**Issue by HoracioNakama** [PyAr/pyarweb#405]
Hola:

Visitando la wiki de ORM de pyar aparecen estos mensajes en los links:

System Message: WARNING/2 (<string> line 21) id2
Inline substitution_reference start-string without end-string.

cuando ingreso este link: http://www.python.org.ar/wiki/ORMs/version/080dd7b%5E

¿Cómo obtuve ese link? Apareció en el buscador de la pagina de Pyar cuando buscaba "Sqlalchemy"

pero si utilizo el link: http://www.python.org.ar/wiki/ORMs que me lleva a la misma pagina (creo), no me aparecen los mensajes en los links.

Adjunto una captura.

![captura de pantalla de 2017-05-01 20 10 25](https://cloud.githubusercontent.com/assets/23756372/25598509/cbfd1a4a-2eab-11e7-848c-590df71afcfa.png)

Tengan buen día!

**Comment by mgaitan** [comment]
@HoracioNakama sucede que la wiki de pyar se migró del sistema moinmoin que se usaba (usando [esta herramienta](https://github.com/mgaitan/moin2git)  que hice yo) y que usaba otro *markup* para formatear las páginas

La version de la página que estas viendo tiene el formato viejo intentando verse como si fuera restructuredText y por eso da todos esos errores de sintaxis. No obstante la version actual de la página está corregida. 

Lo que sí deberiamos hacer es agregar una regla al robots.txt para que los buscadores no indexen las versiones antiguas de las páginas. 

algo asi
 
```
User-agent: *
Disallow: /wiki/*/version/*
```

**Comment by mgaitan** [comment]
O sería mejor simplemente poner un mensaje más destacado en la cabecera avisando que esa no es la última version de la página?

**Comment by edvm** [comment]
@mgaitan no podemos editar (entiendo que usa otro formato) las versiones viejas desde la wiki. Estimo Waliki sabe que esa versión es vieja y por eso ofrece  ir al `current version`. Es posible que waliki vea que es una versión vieja y automáticamente redireccione al `current version`? tiene sentido lo que pregunto? :joy:

**Comment by edvm** [comment]
@gilgamezh esta tarea es para vos? ;) ;) ;)

**Comment by cmdelatorre** [comment]
Esto fue solucionado en la misma wiki: http://www.python.org.ar/wiki/ORMs
