### ISSUE TITLE
Etiquetas/Tags repetidos (sensible a mayúsculas)

### ISSUE THREAD

**Issue by eduzen** [PyAr/pyarweb#407]
Este issue esta relacionado con el #341 
Estuve mirando el código de django-taggit y creo que podemos rápidamente agregar una config para evitar tags repetidos... hoy tenemos `PYTHON` y `python`como tags repetidos.

Ya estuve laburando en la solución. El único problema es que habría que hacer una migración para eliminar en la db estos tags repetidos (o también se puede hacer borrón y cuenta nueva) 
¿qué opinan?

**Comment by cmdelatorre** [comment]
Yo opino que migración para borrar los repetidos es la que va.

**Comment by eduzen** [comment]
Dale, trato de hacerla migración asi lo metemos!

**Comment by edvm** [comment]
@eduzen como viene esto? :)

**Comment by eduzen** [comment]
@edvm la verdad que está complicado la migración, son varias tablas y requiere mucho laburo. Si seguimos por el camino de la migración me bajo. Creo que sigo pensando que es mejor hacer el borrón y cuenta nueva.

**Comment by edvm** [comment]
@eduzen bien, por mi +1 a borron y cuenta nueva. Este issue quedaria entonces en implementar / actualizar el codigo para que no se repitan los tags? (los futuros tags)

**Comment by edvm** [comment]
@eduzen novedades sobre esto? :)

**Comment by eduzen** [comment]
Lo deje para laburarlo en el pycamp!

2018-04-24 11:41 GMT-03:00 Emiliano Dalla Verde Marcozzi <
notifications@github.com>:

**Comment by cmdelatorre** [comment]
Count me in!

Carlos Matías
@py_litox <https://twitter.com/py_litox>

**Comment by cmdelatorre** [comment]
Estamos trabajando en esto con @eduzen, @jualvarez  y @matuu.
Edu va a trabajar en que los Tags se guarden normalizados. Yo voy a trabajar en una migración que limpie un poco los Tags existentes.

El resto de la historia implica hacer cosas en frontend que escapan al alcance de este issue. Estuvimos viendo que implica cambiar la app que estamos usando para ese autosuggest y nadie se quiere meter en ese embrollo de Javascript por ahora

**Comment by edvm** [comment]
@cmdelatorre genial! que hay que hacer en frontend? uno de los chicos fixeo el autosuggest (la parte de js) para que funcionen los tags, el fix es esta mergeado en `dev`: https://github.com/PyAr/pyarweb/pull/412 . No se si es ese el laburo que falta hacer en frontend, o es otra cosa.

**Comment by cmdelatorre** [comment]
Nah, es otra cosa...

**Comment by cmdelatorre** [comment]
Perdón, me faltó mandar el PR con la migración que hice. Ya lo mando.

**Comment by cmdelatorre** [comment]
@eduzen revisa esto porfa: #419
