### ISSUE TITLE
Markup para posts de trabajos

### ISSUE THREAD

**Issue by cmdelatorre** [PyAr/pyarweb#409]
Estaría bueno agregar el editor WYSIWYG, que hay para describir Eventos, en la descripción de las búsquedas de trabajo.  Sanitizar la entrada html https://github.com/PyAr/pyarweb/issues/410 al describir eventos.

**Comment by matuu** [comment]
Voy a trabajar en este issue

**Comment by matuu** [comment]
En realidad, ya está agregado el editor WYSIWYG pero hay un error js de django-taggit-autosuggest que impide que se carguen. Se debería ver así:
![captura de pantalla de 2018-04-07 21-29-35](https://user-images.githubusercontent.com/282628/38461601-1cf5a2da-3aab-11e8-8427-102283ccd53d.png)
Esto ya lo pude arreglar, agrego django-html_sanitizer para este campo y el del #410, o el #410 ya lo están resolviendo?

**Comment by edvm** [comment]
@matuu genial! Te acabo de asignar #410, agregale nomas el sanitizer a este y el del #410  :+1:

**Comment by edvm** [comment]
Fixeado y mergeado a dev en:
https://github.com/PyAr/pyarweb/pull/412
