### ISSUE TITLE
Campo Descripción en App de trabajos acepta HTML

### ISSUE THREAD

**Issue by cmdelatorre** [PyAr/pyarweb#410]
Esa página permite injección de JS, por ejemplo poniendo: 

<script type="text/javascript">
alert("Hola");
</script>

Me parece que es inseguro y deberíamos resolverlo. Tal vez, hacerlo en conjunto con #409

**Comment by edvm** [comment]
good catch @cmdelatorre , ahi lo agregue al project :+1:

**Comment by cmdelatorre** [comment]
PAsa lo mismo en Eventos. Hay un editor WSIWYG pero que permite editar el HTML resultante, Incluso lo interpreta de pecho, mientras uno edita el contenido :disappointed:

**Comment by cmdelatorre** [comment]
En primera instancia hay que decidir si queremos que se puedan formatear los campos de descripción. Yo pienso que si, está bueno. 

En todo caso, hay que sanitizar *siempre* (en el backend) el input que recibimos de los usuarios. 
Eso sería con algo como [django-html_sanitizer](https://github.com/ui/django-html_sanitizer). Lo probé un poco y parece que va por ahí la mano.

**Comment by edvm** [comment]
Fixeado y mergeado a dev en: https://github.com/PyAr/pyarweb/pull/412
