### ISSUE TITLE
Mover app 'tutoring' a un directorio 'deprecado'. 

### ISSUE THREAD

**Issue by edvm** [PyAr/pyarweb#413]
En prod tenemos: http://www.python.org.ar/tutoring/project/
El código esta en prod pero sin uso. Discutir (idealmente en el PyCamp) que van a hacer con esta app, si sacamos el fuente o si se pone en funcionamiento.

**Comment by edvm** [comment]
Sin noticias en PyCamp respecto de esta app. Actualizo el issue para crear un directorio 'deprecated-apps', mover 'tutoring' a este directorio, y ajustar la app para sacar 'tutoring' del `INSTALLED_APPS` y otros lugares donde corresponda (ej: `urls.py`)

**Comment by cmdelatorre** [comment]
deprecated-apps no hace falta. Por algo tenemos Git. Borremos lo que no se usa y listo (siempre se puede encontrar luego). En todo caso, dejemos documentado en algún lado esta operación. Por ejemplo acá mismo.

**Comment by FedericoJurio** [comment]
Teniendo en cuenta el comentario de @cmdelatorre cree el PR https://github.com/PyAr/pyarweb/pull/433 resolver este issue.

**Comment by gilgamezh** [comment]
gracias @FedericoJurio
