### ISSUE TITLE
Ordenar lista de trabajos dando importancia a empresas socias

### ISSUE THREAD

**Issue by facundobatista** [PyAr/pyarweb#417]
Hola!

La lista de trabajo hoy se ordena por timestamp. Necesitamos que se ordene principalmente por un "status de empresa" (que podría ser un número, modificable solamente por admin), y dentro de cada mismo status, por timestamp como ahora

**Comment by eduzen** [comment]
@cmdelatorre @facundobatista @edvm  Yo lo agarró y ahora nos ponemos con @s4msagaz @ambro17

**Comment by eduzen** [comment]
@facundobatista acá está el pull, para que lo revisen.

Lo único que cuando mergemos hay que setear en el admin un valor para las empresas que son parte de la asoc civil

**Comment by eduzen** [comment]
Bueno falta deployar, pero no estaría en open!

**Comment by edvm** [comment]
@eduzen yep, lo muevo a `Done` (de ahi luego saco el listado de cosas que salen en este release `1.0`) :D
