### ISSUE TITLE
dejar de usar el branch de development. 

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/pyarweb#428]
Creo que simplemente nos genera más problemas. propongo cambiar al siguiente modo

- master
- PR siempre a master
- cada merge a master debe resultar en un deploy en staging/beta 
- para hacer un deploy a "producción" generamos un tag de release

@cmdelatorre @eduzen qué opinan?

**Comment by eduzen** [comment]
Me parece buena idea que todos los pull sean directo a master y que si se aprueba el pull el merge acompañe si o si a un deploy en staging. 
También acuerdo lo de los tags de release!

**Comment by gilgamezh** [comment]
si @cmdelatorre nos da un +1 elimino el branch dev y dejo master como default.

**Comment by cmdelatorre** [comment]
Si, de acuerdo con probar ese esquema. Habría que documentarlo apropiadamente para los que quieran colaborar: 
* principalmente acá: https://github.com/PyAr/pyarweb/blob/dev/CONTRIBUTING.md
* y también está esto: https://github.com/PyAr/pyarweb/wiki/Manual-b%C3%A1sico-de-supervivencia-para-colaborar-con-el-sitio-de-PyAr (que no sé si suma o resta)
