### ISSUE TITLE
Warnings en la sección aprendiendo-python

### ISSUE THREAD

**Issue by eamanu** [PyAr/pyarweb#454]
Buenas!

Se ven mensajes de warning

![image](https://user-images.githubusercontent.com/7605307/72683930-e21b7600-3aba-11ea-9f92-7278ef86df8f.png)

Me parece que está relacionado con https://github.com/PyAr/pyarweb/issues/439

**Comment by tzulberti** [comment]
No me queda en claro en que PR lo solucionamos, pero ya esta bien.
