### ISSUE TITLE
En la sección eventos se ve los tags <font style>

### ISSUE THREAD

**Issue by eamanu** [PyAr/pyarweb#455]
![image](https://user-images.githubusercontent.com/7605307/75393486-f0845b00-58cc-11ea-8c83-bef8fffcae46.png)

**Comment by FedericoJurio** [comment]
Cree el PR #456 para solucionar este problema. El form maneja ese campo con la clase `SanitizedCharField`, el problema está en que varias keywords que usa el editor WYSIWYG no están soportadas.

**Comment by tzulberti** [comment]
Close by #456
