### ISSUE TITLE
Actualizar a Django 3.0

### ISSUE THREAD

**Issue by tzulberti** [PyAr/pyarweb#461]
La versión de django que usa pyarweb ya no tiene soporte y hay varias librerias que no funcionan con la misma.

Deberiamos actualizar a la ultima version de django cosa de dejarlo actualizado por los temas de seguridad y otras cosas

**Comment by marcorichetta** [comment]
Cerrado por #471

**Comment by JigyasuRajput** [comment]
Hi, @tzulberti 
It looks like this issue was closed with #471, and the upgrade to Django 3.0 seems to be complete. If there’s any follow-up work or improvements needed, I’d be happy to contribute!

**Comment by facundobatista** [comment]
Good!
