### ISSUE TITLE
Error en contenido en la sección AprendiendoPython

### ISSUE THREAD

**Issue by carpe-diem** [PyAr/pyarweb#464]
al final de la página [¡Quiero Aprender Python!](http://www.python.org.ar/wiki/AprendiendoPython)

![image](https://user-images.githubusercontent.com/1020887/82341991-7c3aee80-99c7-11ea-9107-57fd4721b3ba.png)

**Comment by FedericoJurio** [comment]
Esto mismo está reportado en #454

**Comment by tzulberti** [comment]
Esto fue solucionado en la nueva wiki, que todavía no pusimos en producción. Lo podes ver acá: https://wiki.python.org.ar/aprendiendopython/
