### ISSUE TITLE
No anda el filtrado por tags

### ISSUE THREAD

**Issue by tzulberti** [PyAr/pyarweb#472]
Si se filtran por tags, el mismo no anda correctamente y no se filtra. Por ejemplo, en la siguiente URL seleccione varios tags: https://www.python.org.ar/trabajo/?tag_part-time=1&tag_git=1&tag_google-cloud_1=1&tag_pythonjava_1=1&tag_api-rest_1=1&tag_zmq=1

pero me muestra busquedas que no tienen ese tag

**Comment by pangolp** [comment]
@tzulberti ¿usted sabe si actualmente el problema fue resuelto? Para informar y cerrar el tema en caso de que el error ya no exista. Debido a que tiene un **merged** de un PR, pero nose si fue resuelto el tema.

**Comment by facundobatista** [comment]
Este, y todos los issues que hablen del sistema de cartelera "actual", habría que cerrarlos porque estamos implementando el sistema de cartelera "nuevo" (que se terminará en breve,....)
