### ISSUE TITLE
accesible CAPTCHA

### ISSUE THREAD

**Issue by gilgamezh** [PyAr/pyarweb#479]
También recibimos el mismo pedido de Alejandro <aleguillermero@gmail.com

On Sun, May 9, 2021 at 3:22 AM Victor Sanchez <sanchezvictordaniel@gmail.com> wrote:

Saludos.  Les escribo para solicitar, tengan a bien, implementar la opción de captcha accesible, mediante audio. Formó parte de un grupo de personas muy interesadas en python.  grupo en el que formamos parte personas con discapacidad, entre las cuales hay personas ciegas a las que no les es posible completar el registro a su página. Les agradecería que pudieran ver e implementar esta opción. Sin más y a la espera de una pronta respuesta. me despido Atte.
Sanchez Victor Daniel

**Comment by gilgamezh** [comment]
@marcorichetta  dale metele nomas!

**Comment by marcorichetta** [comment]
Buenas!

Estuve renegando un poco bastante creo pero tuve avances :muscle: 

### Generación del audio
- Para habilitarla es necesario instalar `flite`, en este caso con `apt install flite` bastó.
- Después configure la variable [CAPTCHA_FLITE_PATH](https://django-simple-captcha.readthedocs.io/en/stable/advanced.html#captcha-flite-path) en settings con el path correspondiente.

### Resultado
Se escucha el text to speech pero github mutea los videos parece.

https://user-images.githubusercontent.com/19599150/118071813-e5f19c80-b37e-11eb-9883-6f3ea6f05316.mp4

### Problemas
- No me parece muy usable el tener que abrir otra pestaña para escuchar un audio
- Firefox te pregunta si querés descargar el archivo, no lo reproduce.

### Posibles soluciones
Hay un [issue abierto](https://github.com/mbi/django-simple-captcha/issues/178) para que se pueda reproducir ahí mismo el audio, con los controles del navegador.
La idea es ajustar el template del `CaptchaField` para que use `<audio>` tags y así el navegador lo reconozca como tal.

![imagen](https://user-images.githubusercontent.com/19599150/118072356-00784580-b380-11eb-9996-9ecb57d5f773.png)

Entiendo que no se puede copiar esa solución tan fácilmente porque tenemos la versión 0.5.3 de la librería y el audio y la imagen van juntos dentro del context. Esto se cambió en versiones siguientes.

- Javascript podría ser una vía ya que lo que habría que cambiar sería relativamente simple.
- La otra es modificar alguna de las variables que provee la lib para customizar el HTML que genera que es algo así.

```html
<div class="controls ">
    <a title="Reproducir CAPTCHA de audio" href="/captcha/audio/914cc3d0ddd8b5e3aa4b4c63deb2c2aebc3226c7/">
        <img src="/captcha/image/914cc3d0ddd8b5e3aa4b4c63deb2c2aebc3226c7/" alt="captcha" class="captcha"> 
    </a>
    <input id="id_captcha_0" name="captcha_0" type="hidden" value="914cc3d0ddd8b5e3aa4b4c63deb2c2aebc3226c7">
    <input autocomplete="off" id="id_captcha_1" name="captcha_1" type="text">
</div>
```

Si se me ocurre otra cosa lo comento y si alguien tiene una idea mejor bienvenida sea!

:wave:

**Comment by tzulberti** [comment]
Muchisimas gracias por todo el trabajo.

Hay un [PR ](https://github.com/PyAr/pyarweb/pull/471)para actualizar la version de Django, y ahi actualizo la version de la libraria. Podriamos probarlo con esta version de Django, pero es media vieja por lo que no estoy seguro de que vaya a funcionar

**Comment by marcorichetta** [comment]
Hola Tomás, gracias por responder tan rápido!

Ví ese PR hace un tiempo y pienso estaría buenísimo poder subir la versión.

> Podriamos probarlo con esta version de Django, pero es media vieja por lo que no estoy seguro de que vaya a funcionar
Vos decís que pruebe estos cambios partiendo desde tu rama con Django 3?

También se me ocurrió subir la django-simple-captcha a la v. 0.5.12 para probar esto del audio, ya que en la [0.5.13 levantaron el requirement de Django >= 2.2](https://github.com/mbi/django-simple-captcha/commit/21cd31a30b5c97235dcbd50eeb227ed767d9c542#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L33).

Decime que te parece mejor y lo pruebo.

**Comment by tzulberti** [comment]
👍 a subir la version y ver si funciona

**Comment by marcorichetta** [comment]
Subí la versión de la librería a 0.5.12 y pude configurarla para que el template que usa para el captcha incluya el audio con el tag `<audio>`.

Probé en Firefox Dev, Chromium y Firefox en el celu y pude reproducirlos a todos e incluso registrarme.

### Firefox Dev
<img height=200 width=500 src="https://user-images.githubusercontent.com/19599150/118390724-02076f00-b607-11eb-991a-910e8afd636f.png" />

Hay 2 cosas:
- Para generar el audio es necesario instalar `flite` en la imagen de docker. Yo lo agregué [acá](https://github.com/marcorichetta/pyarweb/blob/issue_479_captcha_accesible/Dockerfile#L4) pero no sé si es el archivo correcto o si debiera ir en el `Dockerfile.prod`
- No configuré [sox](https://django-simple-captcha.readthedocs.io/en/latest/advanced.html#captcha-sox-path) porque no me parece que alguien se tome el trabajo de generar todos los captchas solo para crearse una cuenta. Si se quiere incluir es cuestión de instalar `sox` en el Dockerfile y agregar el setting.

**Comment by tzulberti** [comment]
Muchas gracias por tomarte el tiempo de hacer todas estas pruebas

Sobre las notas:
1. El Dockerfile.prod es lo que usamos en el entorno de producción. La diferencia es que en produccion instalamos algunas dependencias que no instalamos en el entorno de development (en algún momento deberiamos alinear las dependencias)
2. No creo que sea necesario `sox`.

**Comment by marcorichetta** [comment]
> El Dockerfile.prod es lo que usamos en el entorno de producción

Aclaro que flite es una dependencia que se instala por apt, no por pip. 
Lo que necesitaría es, en `Dockerfile.prod`, agregar la linea `RUN apt update && apt install flite` solamente para instalar ese programa.

Si me das el ok, agrego esa línea y hago el PR nomas.

> La diferencia es que en produccion instalamos algunas dependencias que no instalamos en el entorno de development (en algún momento deberiamos alinear las dependencias)

No me parece mal que se diferencien los requirements de dev y de prod, si a eso te referís. Cuál sería el objetivo de alinearlos?

**Comment by marcorichetta** [comment]
@tzulberti Creé el PR pero no los pude agregar como reviewers por eso comento acá.

**Comment by tzulberti** [comment]
Gracias al trabajo de @marcorichetta, esto ya esta en produccion funcionando

**Comment by facundobatista** [comment]
Buenas! Algo en la evolución de los distintos componentes rompió el captcha... si instalo `flite` a mano, se genera un WAV pero 

a) también te ofrece descargarlo, no lo reproduce directamente
b) lo descargo y escucho, y no le entiendo nada :/
c) NO tiene una parte "visual"

@marcorichetta si le podés pegar una mirada, agradecido!

**Comment by marcorichetta** [comment]
@facundobatista confirmo que puedo reproducirlo. Lo veo!

**Comment by facundobatista** [comment]
Hola! @marcorichetta ! No te entendí. ¿Qué cosa podés reproducir... el audio o el problema? ¿Y qué ves.... el captcha o este tema? Gracias :)

**Comment by facundobatista** [comment]
Maravilloso, gracias!
