### ISSUE TITLE
Configuración de un entorno de desarrollo

### ISSUE THREAD

**Issue by pangolp** [PyAr/pyarweb#507]
Hola, buenas tardes. Ayer hice un fork del proyecto, y ya clone el mismo. Al entrar, vi que hay varios archivos de requeriments, y seguí la wiki, para poder intentar desplegar un servidor de desarrollo. Sin embargo, al no tener instalado **PostgreSQL**, no tenia forma de crear la base de datos, y aplicar las migraciones. Edite el fichero de configuración de desarrollo y le agregue, una base de datos **SQLite**. Con eso, pude poner en marcha el servidor, sin embargo, me pregunto si es algo que deberíamos de modificar, me refiero a los archivos del settings, para por ejemplo, incorporar una base de datos local, para poder hacer pruebas, sin la necesidad de instalar ningún otro motor de base de datos. Aguado sus comentarios, para si es necesario, hacer el PR correspondiente, y revisar el tema de las diferencias configuraciones.

**Comment by facundobatista** [comment]
Hola! El PostgreSQL te lo debería levantar el `docker-compose`. No hace falta tener un SQLite (no queremos usar una BD diferente).

Entonces, ¿en qué paso del wiki te trabaste?

**Comment by pangolp** [comment]
No, la verdad es que no vale la pena este issue ya. Lo voy a cerrar, gracias por la recomendación.
