### ISSUE TITLE
Está rota la registración porque no funciona el captcha

### ISSUE THREAD

**Issue by facundobatista** [PyAr/pyarweb#579]
### Comportamiento actual

Tenemos roto el captcha de registración: https://www.python.org.ar/accounts/signup/?next=/

apunta a un audio, ej `https://www.python.org.ar/captcha/audio/95c4483bc56042cb6eb2dfffff81568434f2362d.wav` pero ese archivo no existe :/

Quizás relacionado: https://github.com/PyAr/pyarweb/issues/479

### Comportamiento esperado

El captcha debería funcionar (no me queda bien claro cómo)

### Pasos para reproducir el problema

Ir a https://www.python.org.ar/accounts/signup/?next=/

### pyAr rev. hash/commit

Prod

### Sistema operativo

Linux

**Comment by marcorichetta** [comment]
Bueno, pude reproducir el issue. Parece es por incompatibilidad con Pillow 10.0.0 https://github.com/mbi/django-simple-captcha/issues/219

```py
pyarweb-web-1       | Internal Server Error: /captcha/image/b3e3fc32f891df520cad04bfd91a4e88f384631b/
pyarweb-web-1       | Traceback (most recent call last):
...
pyarweb-web-1       |   File "/usr/local/lib/python3.9/site-packages/captcha/views.py", line 74, in captcha_image
pyarweb-web-1       |     size = getsize(font, text)
pyarweb-web-1       |   File "/usr/local/lib/python3.9/site-packages/captcha/views.py", line 33, in getsize
pyarweb-web-1       |     return font.getsize(text)
pyarweb-web-1       | AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
pyarweb-web-1       | [30/Aug/2023 00:38:04] "GET /captcha/image/b3e3fc32f891df520cad04bfd91a4e88f384631b/ HTTP/1.1" 500 1114
```

**Solución**
- [x] Upgrade de django-simple-captcha a 0.5.18 
- [x] Instalar flite en Dockerfile 
- [ ] Ver por qué no se usa nuestro template custom con el reproductor de audio 

PD:
- El tema reproducción va a seguir siendo en [inglés robótico](https://github.com/PyAr/pyarweb/issues/479#issuecomment-1693354090)

**Comment by marcorichetta** [comment]
PD 2: Para inicializar el proyecto en Docker siguiendo [esta wiki](https://github.com/PyAr/pyarweb/wiki/Instalacion-con-Docker) tuve que reemplazar la imagen ya que 1) `pyarweb` no existe en dockerhub o es privado y 2) `stable-prod` es la imágen más reciente.

```diff
-image: pyarweb
+image: pyar/pyarweb:stable-prod
```

Entiendo que una vez buildeada localmente la imagen (`make start`) esto se soluciona. 
Si seguimos así deberíamos actualizar la wiki. También estaría bueno re-taggear [latest](https://hub.docker.com/r/pyar/pyarweb/tags) en dockerhub con la última versión.
