### ISSUE TITLE
Datos de contactos no son links (clickeables)

### ISSUE THREAD

**Issue by marcorichetta** [PyAr/pyarweb#587]
### Comportamiento actual

Actualmente, al clickear para ver la info de contacto de una oferta, se despliegan los datos pero no son clickeables.

Ejemplo: https://www.python.org.ar/trabajo/senior-python-engineer-remoto/

<img width=350 height=200 src=https://github.com/user-attachments/assets/931d9e52-b332-4dd1-8221-0dec151f31b9 />

### Comportamiento esperado

Los links podrían ser clickeables.
- Web como link normal
- Email con `mailto`
- Teléfono con `tel`

Referencia: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#href

<img width=350 height=200 src=https://github.com/user-attachments/assets/bd15d5dc-7aee-44b8-9d3b-4bcdd4cc84fc />

### Pasos para reproducir el problema

1. Ingresar a https://www.python.org.ar/trabajo/senior-python-engineer-remoto/
2. Clickear en **Ver información de contacto**

### pyAr rev. hash/commit

master

### Sistema operativo

Arch Linux

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
